// swift-tools-version: 6.0
import PackageDescription

// The app is a SwiftPM executable so it can depend on FluidAudio, which is only
// distributed as a Swift package. The Rust core is linked in via linkerSettings —
// build.sh runs cargo first, since SPM has no notion of a cargo build step.
//
// NOTE: the package directory must not be named after a dependency. SPM derives
// the root package's identity from its directory, and a collision makes it look
// for the dependency's products inside itself, failing with a confusing
// "product not found in package" error.
let package = Package(
    name: "Subtitles",
    platforms: [.macOS("14.2")],
    dependencies: [
        .package(url: "https://github.com/FluidInference/FluidAudio.git", exact: "0.15.5"),
        // In-app updates (PLAN.md §23). A binary xcframework: SwiftPM links it,
        // and build.sh has to carry the framework into the bundle by hand.
        .package(url: "https://github.com/sparkle-project/Sparkle.git", exact: "2.9.6"),
    ],
    targets: [
        // Generated by cbindgen during the Rust build.
        .systemLibrary(name: "CSubs", path: "core/include"),
        // The parts of the caption pipeline that are pure data: how a transcript
        // becomes sentences, how a stream becomes pages, how a translated
        // fragment gets its case back. Split out of the app so `swift test` can
        // reach them — every one of these has regressed at least once, and none
        // of them needs AppKit to be exercised.
        .target(name: "CaptionCore", path: "app/captions",
                swiftSettings: [.swiftLanguageMode(.v5)]),
        .executableTarget(
            name: "subtitles",
            dependencies: [
                "CSubs",
                "CaptionCore",
                .product(name: "FluidAudio", package: "FluidAudio"),
                .product(name: "Sparkle", package: "Sparkle"),
            ],
            path: "app/macos",
            // The app predates SwiftPM here and was written against Swift 5
            // semantics; swift-tools-version 6 would otherwise switch it to the
            // Swift 6 language mode and fail on AppKit main-actor isolation.
            // Migrating that is worth doing, but not as a side effect of adding
            // a dependency.
            swiftSettings: [.swiftLanguageMode(.v5)],
            linkerSettings: [
                .unsafeFlags(["-Lcore/target/release", "-lsubs_core"]),
                .linkedFramework("CoreAudio"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreML"),
                .linkedFramework("Accelerate"),
                .linkedFramework("Carbon"),
                // Weak, not linked: Translation.framework does not exist on the
                // 14.2 floor this app still targets. A hard link would refuse to
                // launch there; weak leaves the symbols null and the
                // `@available(macOS 15, *)` code simply never runs.
                .unsafeFlags(["-Xlinker", "-weak_framework", "-Xlinker", "Translation"]),
                // Sparkle is a dynamic framework, the only one here. SwiftPM
                // leaves a copy beside the binary and links with @loader_path,
                // which is right for `.build` and wrong for the bundle, where
                // build.sh puts it in Contents/Frameworks.
                .unsafeFlags(["-Xlinker", "-rpath", "-Xlinker", "@executable_path/../Frameworks"]),
            ]),
        .testTarget(name: "CaptionCoreTests", dependencies: ["CaptionCore"],
                    path: "Tests/CaptionCoreTests",
                    swiftSettings: [.swiftLanguageMode(.v5)]),
    ]
)