// swift-tools-version: 6.0
import PackageDescription

// The app is a SwiftPM executable so it can depend on FluidAudio, which is only
// distributed as a Swift package. The Rust core is linked in via linkerSettings —
// build.sh runs cargo first, since SPM has no notion of a cargo build step.
//
// NOTE: the package directory must not be named after a dependency. SPM derives
// the root package's identity from its directory, and a collision makes it look
// for the dependency's products inside itself, failing with a confusing
// "product not found in package" error.
let package = Package(
    name: "Subtitles",
    platforms: [.macOS("14.2")],
    dependencies: [
        .package(url: "https://github.com/FluidInference/FluidAudio.git", exact: "0.15.5")
    ],
    targets: [
        // Generated by cbindgen during the Rust build.
        .systemLibrary(name: "CSubs", path: "core/include"),
        .executableTarget(
            name: "subtitles",
            dependencies: [
                "CSubs",
                .product(name: "FluidAudio", package: "FluidAudio"),
            ],
            path: "app/macos",
            // The app predates SwiftPM here and was written against Swift 5
            // semantics; swift-tools-version 6 would otherwise switch it to the
            // Swift 6 language mode and fail on AppKit main-actor isolation.
            // Migrating that is worth doing, but not as a side effect of adding
            // a dependency.
            swiftSettings: [.swiftLanguageMode(.v5)],
            linkerSettings: [
                .unsafeFlags(["-Lcore/target/release", "-lsubs_core"]),
                .linkedFramework("CoreAudio"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreML"),
                .linkedFramework("Accelerate"),
                .linkedFramework("Carbon"),
            ]),
    ]
)