//! Safe wrapper over the sherpa-onnx streaming (online) recognizer.
//!
//! Bindings are generated by bindgen at build time (see build.rs) rather than
//! hand-written — PLAN.md D4. The config struct alone has ~17 fields with nested
//! sub-structs; transcribing that by hand is exactly the kind of silent-ABI-skew
//! bug that is miserable to debug.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

mod ffi {
    include!(concat!(env!("OUT_DIR"), "/sherpa.rs"));
}

use std::ffi::{CStr, CString};
use std::path::Path;

pub struct Recognizer {
    rec: *const ffi::SherpaOnnxOnlineRecognizer,
    stream: *const ffi::SherpaOnnxOnlineStream,
    // config holds borrowed pointers; keep the backing strings alive for the
    // lifetime of the recognizer rather than trusting sherpa to have copied them
    _strings: Vec<CString>,
}

// The recognizer is owned and driven by exactly one thread (the ASR worker).
unsafe impl Send for Recognizer {}

/// Model filenames vary across releases ("-chunk-16-left-128", "-epoch-29-avg-9-…"),
/// so locate the three model files by prefix instead of hardcoding names.
/// Spike 0A hit this when the 20M and 2023-06-26 models disagreed on naming.
fn find_model(dir: &Path, prefix: &str, want_int8: bool) -> Result<String, String> {
    let entries = std::fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let mut best: Option<String> = None;
    for e in entries.flatten() {
        let name = e.file_name().to_string_lossy().to_string();
        if !name.starts_with(prefix) || !name.ends_with(".onnx") {
            continue;
        }
        if name.ends_with(".int8.onnx") != want_int8 {
            continue;
        }
        if best.is_none() {
            best = Some(name);
        }
    }
    best.map(|n| dir.join(n).to_string_lossy().to_string())
        .ok_or_else(|| format!("no {prefix}*.onnx (int8={want_int8}) in {}", dir.display()))
}

impl Recognizer {
    pub fn new(model_dir: &str, num_threads: i32, int8: bool) -> Result<Self, String> {
        let dir = Path::new(model_dir);
        if !dir.is_dir() {
            return Err(format!("model dir not found: {model_dir}"));
        }

        // Prefer the requested precision, but fall back to whatever exists: some
        // releases ship int8 weights only, and demanding fp32 makes them look
        // like broken model directories.
        let pick = |prefix: &str, want: bool| -> Result<String, String> {
            find_model(dir, prefix, want).or_else(|_| find_model(dir, prefix, !want))
        };
        let encoder = pick("encoder", int8)?;
        let decoder = pick("decoder", false)?; // fp32 decoder when there is a choice
        let joiner = pick("joiner", int8)?;
        let tokens = dir.join("tokens.txt").to_string_lossy().to_string();
        if !Path::new(&tokens).exists() {
            return Err(format!("missing tokens.txt in {model_dir}"));
        }

        let mut strings = Vec::new();
        let mut cstr = |s: &str| -> *const std::os::raw::c_char {
            let c = CString::new(s).unwrap();
            let p = c.as_ptr();
            strings.push(c);
            p
        };

        let mut cfg: ffi::SherpaOnnxOnlineRecognizerConfig = unsafe { std::mem::zeroed() };
        cfg.feat_config.sample_rate = 16000;
        cfg.feat_config.feature_dim = 80;
        cfg.model_config.transducer.encoder = cstr(&encoder);
        cfg.model_config.transducer.decoder = cstr(&decoder);
        cfg.model_config.transducer.joiner = cstr(&joiner);
        cfg.model_config.tokens = cstr(&tokens);
        cfg.model_config.num_threads = num_threads;
        // Spike 0A Finding 3: the coreml provider was measurably *worse* than cpu
        // (RTF 0.414 vs 0.251) plus a 10 s model-load penalty. Do not "optimise"
        // this to coreml without re-measuring.
        cfg.model_config.provider = cstr("cpu");
        cfg.model_config.debug = 0;
        cfg.decoding_method = cstr("greedy_search");
        cfg.max_active_paths = 4;
        cfg.enable_endpoint = 0;

        let rec = unsafe { ffi::SherpaOnnxCreateOnlineRecognizer(&cfg) };
        if rec.is_null() {
            return Err("SherpaOnnxCreateOnlineRecognizer returned null".into());
        }
        let stream = unsafe { ffi::SherpaOnnxCreateOnlineStream(rec) };
        if stream.is_null() {
            unsafe { ffi::SherpaOnnxDestroyOnlineRecognizer(rec) };
            return Err("SherpaOnnxCreateOnlineStream returned null".into());
        }

        Ok(Recognizer {
            rec,
            stream,
            _strings: strings,
        })
    }

    pub fn accept(&mut self, samples: &[f32], sample_rate: i32) {
        if samples.is_empty() {
            return;
        }
        unsafe {
            ffi::SherpaOnnxOnlineStreamAcceptWaveform(
                self.stream,
                sample_rate,
                samples.as_ptr(),
                samples.len() as i32,
            )
        }
    }

    /// Run every decode step the engine currently has work for.
    pub fn decode(&mut self) {
        unsafe {
            while ffi::SherpaOnnxIsOnlineStreamReady(self.rec, self.stream) != 0 {
                ffi::SherpaOnnxDecodeOnlineStream(self.rec, self.stream);
            }
        }
    }

    /// Current hypothesis as individual tokens.
    ///
    /// Note the C API hands back word starts as a leading ASCII space, not the
    /// U+2581 that appears in tokens.txt (discovered in Spike 0A) — so
    /// concatenating tokens yields correctly spaced text.
    pub fn tokens(&self) -> Vec<String> {
        unsafe {
            let r = ffi::SherpaOnnxGetOnlineStreamResult(self.rec, self.stream);
            if r.is_null() {
                return Vec::new();
            }
            let count = (*r).count as usize;
            let arr = (*r).tokens_arr;
            let mut out = Vec::with_capacity(count);
            if !arr.is_null() {
                for i in 0..count {
                    let p = *arr.add(i);
                    if !p.is_null() {
                        out.push(CStr::from_ptr(p).to_string_lossy().into_owned());
                    }
                }
            }
            ffi::SherpaOnnxDestroyOnlineRecognizerResult(r);
            out
        }
    }

    pub fn reset(&mut self) {
        unsafe { ffi::SherpaOnnxOnlineStreamReset(self.rec, self.stream) }
    }
}

impl Drop for Recognizer {
    fn drop(&mut self) {
        unsafe {
            ffi::SherpaOnnxDestroyOnlineStream(self.stream);
            ffi::SherpaOnnxDestroyOnlineRecognizer(self.rec);
        }
    }
}
