// Generated by tools/vendor-demo.sh from the site's script.js. Do not edit.
// Copy that this script writes into the page lives in <template id="i18n-js">,
// so it can be extracted and translated like any markup string. The literals
// passed here are the English fallback, used when the template is absent.
const I18N = (() => {
  const tpl = document.getElementById('i18n-js');
  const map = {};
  if (tpl) {
    for (const el of tpl.content.querySelectorAll('[data-js]')) {
      map[el.dataset.js] = el.textContent.trim();
    }
  }
  return (name, fallback) => map[name] || fallback;
})();

(function waveFit() {
  const wave = document.getElementById('pod-wave');
  if (!wave || !('ResizeObserver' in window)) return;
  const bars = [...wave.children];
  const n = bars.length;
  if (n < 2) return;
  const fit = () => {
    const dpr = window.devicePixelRatio || 1;
    const width = Math.floor(wave.clientWidth * dpr);
    if (width < n * 2) return;
    // Bars four times the gap, as the stylesheet draws them.
    const unit = width / (n * 4 + (n - 1));
    const gap = Math.max(1, Math.round(unit));
    const bar = Math.max(1, Math.floor((width - (n - 1) * gap) / n));
    const spare = width - n * bar - (n - 1) * gap;
    wave.style.gap = '0px';
    bars.forEach((b, i) => {
      b.style.width = bar / dpr + 'px';
      b.style.marginInlineEnd = i < n - 1 ? (gap + (i < spare ? 1 : 0)) / dpr + 'px' : '0px';
    });
  };
  new ResizeObserver(fit).observe(wave);
  window.addEventListener('resize', fit);
  fit();
})();

// ── searching the ⌥ stack ────────────────────────────────────────────────────
// The app's HistorySearchView, shared by both demos. A field sits at the
// stack's edge touching the live box, drawn as one more box. Click it, or
// press ⌥F while the stack is up, and the stack is pinned for as long as the
// field has the keyboard: it stays up with ⌥ released, so both hands are free
// to type. Typing narrows the stack to the boxes containing the text, with the
// matches lit; clearing the field shows every box again and keeps the pin.
// Escape or a click anywhere outside the stack unpins it, and the stack goes
// back to living under ⌥. The numbers are the app's, at 30pt of text, so in
// em of the boxes.
const stackSearch = (() => {
  const CALM = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // The app's HistorySearch: case and accents fold on both sides, so "ete"
  // finds "été" and "Zurich" finds "Zürich", and every occurrence counts.
  // Folded one code point at a time, keeping where each folded unit came
  // from, so a hit in the folded text maps back to a range of the original.
  const fold = (ch) => ch.normalize('NFD').replace(/\p{M}/gu, '').toLowerCase();
  const folded = (text) => {
    let out = '';
    const starts = [];
    const ends = [];
    let at = 0;
    for (const ch of text) {
      const f = fold(ch);
      for (let k = 0; k < f.length; k++) { starts.push(at); ends.push(at + ch.length); }
      out += f;
      at += ch.length;
    }
    return { text: out, starts: starts, ends: ends };
  };
  // Every place `query` occurs in `text`, as [from, to) of the original. An
  // empty query matches nowhere: an empty field means "show everything", which
  // is the caller's decision, not a match on every box.
  const ranges = (query, text) => {
    const q = folded(query).text;
    if (!q) return [];
    const t = folded(text);
    const hits = [];
    let from = 0;
    for (;;) {
      const i = t.text.indexOf(q, from);
      if (i < 0) break;
      hits.push([t.starts[i], t.ends[i + q.length - 1]]);
      from = i + q.length;
    }
    return hits;
  };
  const matches = (text, query) => !query || ranges(query, text).length > 0;
  // `text` into `el`, with the hits wrapped so they can be lit. A background
  // changes no glyph's advance, so a box measures the same lit or not.
  const write = (el, text, query) => {
    el.textContent = '';
    let at = 0;
    ranges(query, text).forEach((hit) => {
      if (hit[0] > at) el.append(text.slice(at, hit[0]));
      const lit = document.createElement('span');
      lit.className = 'hist-hit';
      lit.textContent = text.slice(hit[0], hit[1]);
      el.append(lit);
      at = hit[1];
    });
    if (at < text.length) el.append(text.slice(at));
  };

  // The app's SpringValue: one number on a spring, ticked once a frame with
  // the interval the frame actually took, integrated over fixed substeps so
  // it is the same spring at 60 and 120 Hz. The defaults are the search
  // pill's: about a quarter of a second with a small overshoot, quick enough
  // to feel attached to the click, soft enough to read as a spring. A
  // retarget mid-flight keeps its velocity, so an Escape halfway through
  // opening turns round rather than jumping.
  class Spring {
    constructor(value, stiffness, ratio) {
      this.value = value;
      this.target = value;
      this.velocity = 0;
      this.k = stiffness || 700;
      this.c = 2 * (ratio || 0.74) * Math.sqrt(this.k);
      this.frame = 0;
      this.last = 0;
      this.onTick = null;
    }
    snap(value) {
      cancelAnimationFrame(this.frame);
      this.frame = 0;
      this.velocity = 0;
      this.value = value;
      this.target = value;
    }
    animate(target) {
      if (Math.abs(target - this.target) <= 0.5
          && (this.frame || Math.abs(target - this.value) <= 0.5)) return;
      this.target = target;
      if (this.frame) return;
      this.last = 0;
      this.frame = requestAnimationFrame((t) => this.tick(t));
    }
    tick(now) {
      // Clamped: the first tick has no predecessor, and a stall must not be
      // integrated as one enormous step.
      const dt = this.last ? Math.min(Math.max((now - this.last) / 1000, 1 / 240), 1 / 30) : 1 / 120;
      this.last = now;
      let left = dt;
      while (left > 0) {
        const step = Math.min(1 / 480, left);
        this.velocity += (-this.k * (this.value - this.target) - this.c * this.velocity) * step;
        this.value += this.velocity * step;
        left -= step;
      }
      if (Math.abs(this.value - this.target) < 0.3 && Math.abs(this.velocity) < 8) {
        this.snap(this.target);
      } else {
        this.frame = requestAnimationFrame((t) => this.tick(t));
      }
      if (this.onTick) this.onTick(this.value);
    }
  }

  let instances = 0;

  // The pill, put in the stage next to `history`. The demo lays it out and
  // says when the stack is up; this owns the field, the pin and the query.
  //   onPin()          the field took the keyboard: the stack is now held up
  //   onQuery()        the text changed: repaint, narrowed to it, parked
  //   onUnpin(hadQuery) the keyboard went back: the stack answers to ⌥ again
  const attach = (opts) => {
    const history = opts.history;
    const n = ++instances;
    const el = document.createElement('div');
    el.className = 'demo-search';
    el.innerHTML =
      '<svg class="ds-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" aria-hidden="true">'
      + '<circle cx="10.4" cy="10.4" r="6.8"/><path d="M15.5 15.5 21.4 21.4"/></svg>'
      + '<input class="ds-field" type="text" placeholder="Search" aria-label="Search" tabindex="-1"'
      + ' autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">'
      + '<span class="ds-hint" aria-hidden="true">⌥F</span>'
      + '<button type="button" class="ds-clear" tabindex="-1" aria-label="Clear">'
      + '<svg viewBox="0 0 24 24" aria-hidden="true"><mask id="ds-x' + n + '"><rect width="24" height="24" fill="#fff"/>'
      + '<path d="M8.5 8.5l7 7M15.5 8.5l-7 7" stroke="#000" stroke-width="2.4" stroke-linecap="round"/></mask>'
      + '<circle cx="12" cy="12" r="10" fill="currentColor" mask="url(#ds-x' + n + ')"/></svg></button>'
      // For measuring the closed pill: the placeholder and the hint in their
      // own fonts, laid out but never seen.
      + '<span class="ds-measure" aria-hidden="true">Search</span>'
      + '<span class="ds-measure ds-hint" aria-hidden="true">⌥F</span>';
    history.parentNode.insertBefore(el, history);
    const field = el.querySelector('.ds-field');
    const icon = el.querySelector('.ds-icon');
    const clear = el.querySelector('.ds-clear');
    const measure = el.querySelectorAll('.ds-measure');

    let focused = false;
    let query = '';
    let visible = false;
    let starved = false;
    const expanded = () => focused || query !== '';

    const spring = new Spring(0);
    spring.onTick = (w) => { el.style.width = Math.round(w) + 'px'; };

    const num = (v) => parseFloat(v) || 0;
    const em = () => num(getComputedStyle(history).fontSize) || 16;
    // Closed: exactly the icon, the word and the hint. Open: the app's 220pt
    // or 0.55 of the stack, whichever is wider, never wider than the stack.
    const compactWidth = () => {
      const cs = getComputedStyle(el);
      const gap = num(cs.columnGap);
      // The icon is SVG, which has no offsetWidth.
      return num(cs.paddingLeft) + icon.getBoundingClientRect().width + gap + measure[0].offsetWidth
        + Math.round(em() * 0.133) + gap + measure[1].offsetWidth + num(cs.paddingRight);
    };
    const openWidth = (stackWidth) =>
      Math.min(stackWidth, Math.max(Math.round(em() * 7.33), Math.round(stackWidth * 0.55)));

    // A pill while idle, the full field while in use, and the change between
    // them sprung, so the field is seen to open out of the pill rather than
    // replace it. Only while the stack is up: a stack arriving on screen
    // builds the field at the width it should already have.
    const layout = (stackWidth, animate) => {
      el.classList.toggle('is-open', expanded());
      const width = expanded() ? openWidth(stackWidth) : Math.min(stackWidth, compactWidth());
      if (animate && !CALM) spring.animate(width);
      else { spring.snap(width); spring.onTick(width); }
    };
    const place = (left, above, near) => {
      el.style.left = left;
      if (above) { el.style.top = 'auto'; el.style.bottom = near; }
      else { el.style.bottom = 'auto'; el.style.top = near; }
    };
    const setVisible = (on) => { visible = on; el.classList.toggle('is-visible', on); };
    const setBelow = (on) => el.classList.toggle('is-below', on);
    // Nowhere to put the stack: it leaves the screen, keyboard included, and
    // comes back with it. Not an outside click, so the pin survives it.
    const setStarved = (on) => {
      if (starved === on) return;
      starved = on;
      el.classList.toggle('is-starved', on);
      if (!on && focused && document.activeElement !== field) field.focus();
    };
    // The stack opening: the pill is the nearest thing to the live box, so it
    // rises first and the boxes follow it.
    const rise = () => {
      el.classList.remove('is-rising');
      void el.offsetWidth;
      el.classList.add('is-rising');
      el.addEventListener('animationend', () => el.classList.remove('is-rising'), { once: true });
    };

    const setQuery = (text) => {
      query = text;
      el.classList.toggle('has-text', query !== '');
    };
    const changed = () => { setQuery(field.value); opts.onQuery(); };

    // Give the keyboard back and let the stack answer to ⌥ again. The field
    // is emptied whichever way this came. The boxes are left as the search
    // had them: the usual next step is the stack fading out, and what fades
    // should be what was on screen.
    const unpin = () => {
      if (!focused && query === '') return;
      const hadQuery = query !== '';
      focused = false;
      field.value = '';
      setQuery('');
      if (document.activeElement === field) field.blur();
      opts.onUnpin(hadQuery);
    };

    field.addEventListener('focus', () => {
      if (focused) return;
      focused = true;
      opts.onPin();
    });
    field.addEventListener('input', changed);
    field.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') { e.preventDefault(); unpin(); return; }
      if (!e.altKey || e.metaKey || e.ctrlKey) return;
      // ⌥ is what raised the stack, so it is still down as the first letters
      // of a search are typed, and ⌥ with a letter is the layout's alternate
      // character: "an" arrives as "åñ". Stripped from anything that would
      // type a character, and left on everything else, so ⌥⌫ and ⌥← still
      // edit the way they do in any field. ⌥F is the hotkey and types nothing.
      let ch = null;
      const letter = /^Key([A-Z])$/.exec(e.code);
      if (letter) ch = e.shiftKey ? letter[1] : letter[1].toLowerCase();
      else if (/^Digit[0-9]$/.test(e.code)) ch = e.code.slice(-1);
      else if (e.code === 'Space') ch = ' ';
      if (!ch) return;
      e.preventDefault();
      if (e.code === 'KeyF') return;
      field.setRangeText(ch, field.selectionStart, field.selectionEnd, 'end');
      changed();
    });
    // The keyboard went elsewhere: a click on the page, another window. Either
    // is an outside click as far as the pin is concerned.
    field.addEventListener('blur', () => { if (focused && !starved) unpin(); });
    // A click on the pill is a click into the field; on the ✕, one that
    // empties it and keeps the keyboard for the next word; on a box in the
    // stack, inside the panel, so the pin stays. mousedown rather than
    // pointerdown, which is the one Safari lets cancel a focus change.
    clear.addEventListener('mousedown', (e) => e.preventDefault());
    clear.addEventListener('click', () => { field.value = ''; changed(); field.focus(); });
    el.addEventListener('mousedown', (e) => {
      if (e.target === field || clear.contains(e.target)) return;
      e.preventDefault();
      field.focus();
    });
    el.addEventListener('click', (e) => {
      if (e.target === field || clear.contains(e.target)) return;
      field.focus();
    });
    history.addEventListener('mousedown', (e) => { if (focused) e.preventDefault(); });
    // ⌥F, only while the stack is up: the rest of the time it belongs to
    // whatever is in front.
    window.addEventListener('keydown', (e) => {
      if (!e.altKey || e.metaKey || e.ctrlKey || e.code !== 'KeyF') return;
      if (!visible || starved) return;
      e.preventDefault();
      if (!focused) field.focus();
    });
    // Another window took the front. The browser would hand the field its
    // focus back on return, and with it the pin, so it is let go for good.
    window.addEventListener('blur', () => {
      unpin();
      setTimeout(() => { if (document.activeElement === field) field.blur(); }, 0);
    });

    return {
      el: el,
      get query() { return query; },
      get pinned() { return focused; },
      matches: (text) => matches(text, query),
      write: (node, text) => write(node, text, query),
      layout: layout,
      place: place,
      setVisible: setVisible,
      setBelow: setBelow,
      setStarved: setStarved,
      height: () => el.offsetHeight,
      rise: rise,
      unpin: unpin,
      // For the recordings' epilogue, which has no hands: the keyboard into the
      // field, and text into it a piece at a time, as if typed.
      focus: () => field.focus(),
      type: (text) => { field.value += text; changed(); },
    };
  };

  // The app's originXSpring and originYSpring. The live box hugs its text
  // and grows a line at a time as a sentence wraps, and a stack that jumped
  // the line with it read as a jolt; the box itself stays put, since it
  // changes several times a second and is what is being read, and the stack
  // and its pill follow it on a stiff spring, a tenth of a second behind, no
  // overshoot. Straight there when the stack is arriving, since there is
  // nowhere for it to be coming from. In px of the stage, where the demos
  // used to write percentages: the target is recomputed whenever the box
  // moves, which is what the percentages were for.
  const follow = (history, search) => {
    const x = new Spring(0, 900, 0.9);
    const y = new Spring(0, 900, 0.9);
    let above = true;
    let block = 0;
    const lay = () => {
      const left = Math.round(x.value) + 'px';
      const near = Math.round(y.value);
      history.style.left = left;
      search.place(left, above, near + 'px');
      if (above) { history.style.top = 'auto'; history.style.bottom = (near + block) + 'px'; }
      else { history.style.bottom = 'auto'; history.style.top = (near + block) + 'px'; }
    };
    x.onTick = lay;
    y.onTick = lay;
    // `left` is the live box's centre and `near` the stack's edge nearest it,
    // both from the stage's own edges; `gapBlock` is the pill and the gap
    // past it, where the boxes start.
    return (left, near, isAbove, gapBlock, animate) => {
      above = isAbove;
      block = gapBlock;
      if (animate && !CALM) { x.animate(left); y.animate(near); }
      else { x.snap(left); y.snap(near); }
      lay();
    };
  };

  return { attach: attach, follow: follow };
})();

// Writing, in every window that is a document. While such a window is in
// front the caret moves: a notes page or a Word, Docs or Granola document
// grows a line under the last one, the code editor adds tokens to a new line,
// Numbers fills the selected cell and steps down the column. Nothing is
// typed in words, so nothing here needs translating; the skeleton lines grow
// the way the ones already there were drawn. Behind another window a document
// holds still, as it does on a real desktop with the focus elsewhere.
(function liveWriting() {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  const rand = (a, b) => a + Math.random() * (b - a);
  const pick = (list) => list[Math.floor(Math.random() * list.length)];

  // Whether a demo is on screen, so nothing is drawn where nobody can see it.
  const onScreen = new WeakMap();
  const watch = 'IntersectionObserver' in window
    ? new IntersectionObserver((entries) => entries.forEach((e) => onScreen.set(e.target, e.isIntersecting)), { threshold: 0.15 })
    : null;
  const screenOf = (el) => el.closest('.demo-screen');
  const awake = (win) => {
    const screen = screenOf(win);
    if (!screen) return false;
    if (watch && !onScreen.has(screen)) { onScreen.set(screen, true); watch.observe(screen); }
    return win.classList.contains('is-front') && !document.hidden && onScreen.get(screen) !== false;
  };

  // A writer is a function returning the delay before its next step.
  const run = (win, step) => {
    const tick = () => {
      const wait = awake(win) ? step() : 300;
      setTimeout(tick, wait);
    };
    setTimeout(tick, rand(400, 1200));
  };

  // ── documents: a line grows under the caret ──────────────────────────
  document.querySelectorAll('.notes-doc, .lw-doc').forEach((doc) => {
    const caret = doc.querySelector(':scope > .notes-caret');
    const win = doc.closest('.demo-window');
    if (!caret || !win) return;
    // The section being written: the run of lines just above the caret. It
    // may grow by two before the oldest line goes, so the page keeps its height.
    const section = () => {
      const out = [];
      let el = row.previousElementSibling;
      while (el && el.tagName === 'I') { out.unshift(el); el = el.previousElementSibling; }
      return out;
    };
    const row = document.createElement('span');
    row.className = 'lw-write';
    const line = document.createElement('i');
    line.style.width = '0%';
    row.append(line, caret);
    doc.append(row);
    const limit = section().length + 2;
    let width = 0;
    let target = rand(55, 96);
    run(win, () => {
      width = Math.min(target, width + rand(2.5, 6.5));
      line.style.width = width + '%';
      if (width < target) return rand(110, 190);
      // The line is done: it joins the page, and a fresh one starts.
      const done = line.cloneNode();
      row.before(done);
      const lines = section();
      if (lines.length > limit) lines[0].remove();
      width = 0;
      line.style.width = '0%';
      target = Math.random() < 0.15 ? rand(28, 50) : rand(55, 96);
      return rand(350, 700);
    });
  });

  // ── the code editor: tokens land on a new line ───────────────────────
  document.querySelectorAll('.lw-lines').forEach((lines) => {
    const win = lines.closest('.demo-window');
    if (!win) return;
    const limit = lines.children.length;
    const caret = document.createElement('span');
    caret.className = 'notes-caret lw-caret-code';
    let current = null;
    let count = 0;
    let want = 0;
    run(win, () => {
      if (!current) {
        current = document.createElement('span');
        current.className = 'lw-line';
        current.style.paddingLeft = pick([6, 12, 12, 18]) + '%';
        current.append(caret);
        lines.append(current);
        while (lines.children.length > limit) lines.firstElementChild.remove();
        count = 0;
        want = Math.floor(rand(2, 6));
        return rand(200, 400);
      }
      const tok = document.createElement('i');
      tok.className = 'lw-tok-' + pick(['p', 'p', 'p', 'k', 't', 'f', 's', 'n']);
      tok.style.width = rand(3, 12).toFixed(1) + '%';
      caret.before(tok);
      count++;
      if (count < want) return rand(220, 420);
      // Line finished; a beat, then the next one.
      current = null;
      return rand(450, 900);
    });
  });

  // ── the spreadsheet: the selected cell fills, then the one below ─────
  document.querySelectorAll('.lw-sheet').forEach((sheet) => {
    const win = sheet.closest('.demo-window');
    const label = sheet.querySelector('.lw-formula-bar span');
    const bar = sheet.querySelector('.lw-formula-bar i');
    const cells = [...sheet.querySelectorAll('.lw-cell')];
    const cols = 6;
    if (!win || !cells.length) return;
    let at = cells.findIndex((c) => c.classList.contains('is-sel'));
    if (at === -1) at = 0;
    let fill = cells[at].querySelector('i');
    let width = parseFloat(fill.style.width) || 0;
    let target = width || rand(40, 75);
    let phase = 'fill';
    const name = (i) => 'ABCDEF'[i % cols] + (Math.floor(i / cols) + 1);
    run(win, () => {
      if (phase === 'fill') {
        width = Math.min(target, width + rand(4, 9));
        fill.style.width = width + '%';
        if (bar) bar.style.width = (width * 0.6) + '%';
        if (width < target) return rand(90, 160);
        phase = 'move';
        return rand(400, 800);
      }
      // Return: the selection steps down the column, wrapping at the bottom.
      cells[at].classList.remove('is-sel');
      at = (at + cols) % cells.length;
      cells[at].classList.add('is-sel');
      if (label) label.textContent = name(at);
      fill = cells[at].querySelector('i');
      width = 0;
      fill.style.width = '0%';
      target = rand(40, 75);
      phase = 'fill';
      return rand(200, 350);
    });
  });
})();

(function menuBarClock() {
  const el = document.getElementById('mb-time');
  if (!el) return;

  // macOS shows weekday, date and time in the user's own locale.
  const fmt = new Intl.DateTimeFormat(navigator.language || 'en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    hour: 'numeric',
    minute: '2-digit',
  });

  let timer;
  const tick = () => {
    el.textContent = fmt.format(new Date());
    // Re-arm on the next minute boundary rather than polling every second.
    clearTimeout(timer);
    timer = setTimeout(tick, 60000 - (Date.now() % 60000) + 50);
  };

  tick();
  // A backgrounded tab throttles timers, so resync when it comes back.
  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) tick();
  });
})();

(function captionDemo() {
  const box = document.getElementById('caption-box');
  const out = document.getElementById('caption-text');
  const live = document.getElementById('caption-live');
  const glyph = document.getElementById('mb-glyph');
  const switcher = document.getElementById('switcher');
  const windows = document.querySelectorAll('.demo-window');
  if (!box || !out) return;

  const APPS = {
    meeting: I18N('app.meeting', 'Meetings'),
    notes: I18N('app.notes', 'Notes'),
    player: I18N('app.player', 'Player'),
  };

  // Every icon carries its own name, and only the selected one shows it. That is
  // what makes the label move with the selection, and it is why the panel's
  // width is the icons' business alone: the label is out of flow, so a long app
  // name cannot stretch the thing it is labelling.
  windows.length && switcher.querySelectorAll('.sw-app').forEach((el) => {
    const label = el.querySelector('.sw-name');
    if (label) label.textContent = APPS[el.dataset.app];
  });

  // The transport runs only while the player is the window in front, and runs
  // faster than real time on purpose: a scene lasts about a dozen seconds, and a
  // real playhead would not visibly move in that. The clock counting up is the
  // part people read as "this is playing", so that is the part that has to move.
  const CALM = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // Who is talking, handed round the tiles the way it goes in a real call:
  // never straight back to the same person, and held for an uneven beat,
  // because a fixed rotation reads as a carousel rather than a conversation.
  const speakers = (() => {
    const tiles = [...document.querySelectorAll('.win-meeting .tile')];
    let timer = null;
    let at = 0;
    const hand = (to) => {
      at = to;
      tiles.forEach((t, i) => t.classList.toggle('is-speaking', i === at));
    };
    const step = () => {
      hand((at + 1 + Math.floor(Math.random() * (tiles.length - 1))) % tiles.length);
      timer = setTimeout(step, 2100 + Math.random() * 1700);
    };
    let running = false;
    return (on) => {
      // Only on the change. This is called on every switch now, not just when
      // the call fronts, and re-running it while the call was already talking
      // handed the ring back to the first tile each time.
      if (on === running) return;
      running = on;
      clearTimeout(timer);
      // Stopping used to mean stopping the hand-off and nothing else, which left
      // whoever was talking wearing the ring. On a stack that did not matter,
      // because the call was behind one window and barely visible; fanned out it
      // is a third of the screen, and a ring pulsing away under the podcast said
      // a meeting was live in a scene about a podcast. Put the tiles back to
      // nobody speaking, and the window goes quiet with the scene.
      if (!on || !tiles.length) {
        tiles.forEach((t) => t.classList.remove('is-speaking'));
        return;
      }
      // Somebody is talking the moment the call is in front. Reduced motion gets
      // that as a still ring: it is who is speaking, not an animation.
      hand(0);
      if (CALM) return;
      timer = setTimeout(step, 1900);
    };
  })();

  const playhead = (() => {
    const fill = document.getElementById('pod-fill');
    const clock = document.getElementById('pod-elapsed');
    const bars = [...document.querySelectorAll('#pod-wave i')];
    const START = 18 * 60 + 24;   // 18:24, where the markup starts
    const TOTAL = 41 * 60 + 7;    // 41:07
    const RATE = 4;               // seconds of episode per second of demo
    let timer = null;
    let at = START;

    const mmss = (s) =>
      Math.floor(s / 60) + ':' + String(Math.floor(s % 60)).padStart(2, '0');

    const paint = () => {
      const pct = at / TOTAL;
      if (fill) fill.style.width = (pct * 100).toFixed(2) + '%';
      if (clock) clock.textContent = mmss(at);
      const played = Math.round(pct * bars.length);
      bars.forEach((b, i) => b.classList.toggle('is-played', i < played));
    };

    let running = false;
    return (on) => {
      if (!bars.length || CALM) return;
      // Only on the change, for the same reason as the speakers above: the
      // episode now runs on behind the notes, and restarting it every time
      // something else fronted pinned the clock to 18:24.
      if (on === running) return;
      running = on;
      clearInterval(timer);
      if (!on) return;
      at = START;   // every time it starts playing again, it starts here
      paint();
      timer = setInterval(() => {
        // A backgrounded tab should not run the episode on without anybody
        // watching, or coming back to it shows a clock that has raced ahead.
        if (document.hidden) return;
        at = Math.min(TOTAL, at + RATE);
        paint();
      }, 1000);
    };
  })();

  // Which window is actually in front, updated the moment it fronts rather than
  // once a switch has finished: a switch interrupted by a second click has
  // already fronted its window, and a loop carrying that in a local of its own
  // would open the next ⌘-tab panel on the wrong app.
  let frontApp = 'meeting';

  // Back to front, and the only thing that decides what covers what. The three
  // windows used to share one z-index with the front one lifted above them, so
  // everything behind fell back on the order it happens to sit in the markup:
  // raising the notes also carried the podcast over the call, because the
  // podcast is written last. A desktop does not work that way. Whatever you
  // raise goes on top and the rest keep the order they were already in, so the
  // stack is a record of what you have looked at, however you got there: the
  // scene loop, the buttons under it, a click on a window, or a drag by its
  // title bar all arrive here.
  const stack = ['notes', 'player', 'meeting'];
  // Two of the three windows make a sound, and the one higher in the stack is
  // the one making it: switching between them hands the sound over rather than
  // stopping it, and the notes never take it, so something is always playing.
  const playingApp = () =>
    stack.indexOf('meeting') > stack.indexOf('player') ? 'meeting' : 'player';

  const restack = (app) => {
    const at = stack.indexOf(app);
    if (at !== -1) stack.splice(at, 1);
    stack.push(app);
    const playing = playingApp();
    windows.forEach((w) => {
      // 1 to 3, well under the switcher at 6 and the caption at 10, both of
      // which are above every window by definition.
      w.style.setProperty('--z', stack.indexOf(w.dataset.app) + 1);
      w.classList.toggle('is-playing', w.dataset.app === playing);
    });
  };

  const mbApp = document.getElementById('mb-app');
  const APP_NAMES = { meeting: 'Meetings', notes: 'Notes', player: 'Player' };
  const front = (app) => {
    frontApp = app;
    restack(app);
    // The menu bar names the app in front, as the real one does, with the
    // same name the switcher shows for it.
    if (mbApp) mbApp.textContent = I18N('app.' + app, APP_NAMES[app]);
    windows.forEach((w) => w.classList.toggle('is-front', w.dataset.app === app));
    // Both on the same rule as the class above, and neither on being in front:
    // fronting the notes leaves whichever was playing still playing behind them.
    playhead(playingApp() === 'player');
    speakers(playingApp() === 'meeting');
  };
  const select = (app) => {
    switcher.querySelectorAll('.sw-app').forEach((el) =>
      el.classList.toggle('is-selected', el.dataset.app === app)
    );
  };

  // Three scenes: the call, whatever you switch to while it keeps playing, and
  // the podcast. The captions are what the audio is saying.
  const SCENES = [
    {
      app: 'meeting',
      lines: [
        I18N('line.meeting1', 'Universal subtitles for any app, live on your Mac.'),
        I18N('line.meeting2', 'In a meeting, second language or not, one missed word costs you the next three.'),
        I18N('line.meeting3', 'So the captions run live, over the call, while people are still talking.'),
      ],
    },
    {
      app: 'notes',
      lines: [
        I18N('line.notes1', 'Switch to your notes and the meeting carries on without you watching it.'),
        I18N('line.notes2', 'The overlay stays above every window, so you keep the thread.'),
      ],
    },
    {
      app: 'player',
      lines: [
        I18N('line.player1', 'The same for a podcast, a lecture, or a video.'),
        I18N('line.player2', 'And none of it leaves the Mac: it runs on the Neural Engine, on-device.'),
      ],
    },
  ];

  // An epilogue for the recordings, off on the site: the stack and its search,
  // narrated. The capture sets window.SUBTITLES_EPILOGUE to two lines, said
  // before the podcast's last: the stack rises as ⌥ is said in the first, the
  // field opens and a word goes in as ⌥F is said in the second, and both are
  // let go under "none of it leaves the Mac", which then closes the loop as it
  // always did. Without it the loop is the three scenes it always was; the
  // scene bar has no fourth segment and ⌥ is the reader's.
  const EPILOGUE = Array.isArray(window.SUBTITLES_EPILOGUE) && window.SUBTITLES_EPILOGUE.length === 2
    ? window.SUBTITLES_EPILOGUE.map(String)
    : null;

  front(SCENES[0].app);
  select(SCENES[0].app);
  if (glyph) glyph.classList.add('is-live');

  if (CALM) {
    // No loop to unwind — the scene is just what is on screen, so the bar places
    // it directly. The buttons are still worth having: they are the only way
    // through the three scenes when nothing is animating.
    out.textContent = SCENES[0].lines[0];
    box.classList.add('is-visible');
    [...document.querySelectorAll('.demo-scenes .scene-button')].forEach(
      (button, index) =>
        button.addEventListener('click', () => {
          front(SCENES[index].app);
          out.textContent = SCENES[index].lines[0];
          document
            .querySelectorAll('.demo-scenes .scene-button')
            .forEach((b, i) =>
              b.setAttribute('aria-current', i === index ? 'true' : 'false')
            );
        })
    );
    return;
  }

  const WORD_MS = 130;   // roughly conversational pace
  const JITTER = 80;
  const GAP_MS = 500;    // blank between boxes
  // A finished box holds long enough to actually be read: a base beat plus
  // time per word, so a long caption is not gone before you reach the end.
  const holdFor = (words) => Math.min(1500 + words * 130, 4200);

  // One loop for the lifetime of the page. It parks on `paused` instead of
  // returning, because restarting it on every scroll-back stacked a second
  // copy on top of the first and the two raced the caption text.
  let onScreen = true;
  let paused = false;
  const sync = () => { paused = !onScreen || document.hidden; };

  // Set by a click on a scene button or on one of the windows; the loop unwinds
  // at its next beat and picks that scene up from the top. `direct` is the
  // difference between the two: the buttons are a request to go somewhere, and
  // watching the ⌘-tab get there is the point of them, while clicking a window
  // is reaching for that window — the machinery in between would be in the way.
  let jump = null;
  const JUMPED = Symbol('jumped');

  // Every wait currently in flight, so a click can end them all now rather than
  // when their timer says so. Without it a click landed whenever the current
  // wait happened to end, and a caption that has finished typing holds for up to
  // 4.2 seconds — long enough to read as nothing having happened.
  const waking = new Set();
  const wait = (ms) => new Promise((resolve) => {
    const finish = () => { clearTimeout(timer); waking.delete(finish); resolve(); };
    const timer = setTimeout(finish, ms);
    waking.add(finish);
  });
  const wake = () => { [...waking].forEach((finish) => finish()); };

  async function step(ms) {
    await wait(ms);
    while (paused && !jump) await wait(150);
    if (jump) throw JUMPED;
  }

  // One subtitle box: types out, holds long enough to read, clears. The app
  // pages the same way, and shows the newest word dim until it commits.
  //
  // `from` and `to` are the slice of the scene's bar this caption is worth. The
  // bar is walked across it in two moves — one for the typing, one for the hold
  // — because those are the only two moments the loop knows how long the next
  // stretch will take. The second starts from wherever the first actually got
  // to, so the jitter in the typing corrects itself rather than piling up.
  async function say(line, from, to) {
    const words = line.split(' ');
    const hold = holdFor(words.length);
    const typing = words.length * (WORD_MS + JITTER / 2);
    const typed = from + (to - from) * (typing / (typing + hold + GAP_MS));

    out.textContent = '';
    live.textContent = '';
    box.classList.add('is-visible');
    progress(typed, typing);

    for (let i = 0; i < words.length; i++) {
      if (jump) throw JUMPED;
      out.textContent = i ? words.slice(0, i).join(' ') + ' ' : '';
      live.textContent = words[i];
      // A comma or full stop gets a beat, the way speech does.
      const punctuated = /[,.;:—]$/.test(words[i]);
      await step(WORD_MS + Math.random() * JITTER + (punctuated ? 180 : 0));
    }

    // Everything commits once the utterance ends.
    out.textContent = line;
    live.textContent = '';
    progress(to, hold + GAP_MS);

    await step(hold);
    box.classList.remove('is-visible');
    // The page has closed. The app records it here too, at the fade, because
    // fading is precisely when somebody looked away and will want it back.
    closePage(line);
    await step(GAP_MS);
  }

  // ⌘-tab: panel up on the current app, selection moves, window fronts as the
  // panel drops — which is when you'd release the key.
  async function switchTo(to) {
    select(frontApp);
    switcher.classList.add('is-visible');
    await step(340);
    select(to);
    await step(560);
    front(to);
    switcher.classList.remove('is-visible');
    await step(220);
  }

  // Both halves of a concurrent pair have to finish before the loop moves on,
  // including when one of them threw: awaiting Promise.all would leave the other
  // running against a loop that has already unwound, and its rejection
  // unhandled a beat later.
  async function both(a, b) {
    const settled = await Promise.allSettled([a, b]);
    const failed = settled.find((result) => result.status === 'rejected');
    if (failed) throw failed.reason;
  }

  // The recordings' epilogue, see EPILOGUE above. Each move lands as the word
  // for it is said, which is what makes it read as the narration doing it: the
  // stack rises as ⌥ comes up in the first line, the field opens as ⌥F does in
  // the second, and a word the stack holds twice by then, in the call's second
  // line and the notes' first, goes in a letter at a time, so the search is
  // seen to narrow seven boxes to two. The scene bar holds where the podcast's
  // first line left it: the epilogue has no segment of its own.
  // ⌥ goes first: unpinning while it still counted as held would repaint the
  // stack with every box back, and that is what would fade. Let go of both
  // at once and what fades is what the search had on screen.
  const endEpilogue = () => {
    if (!search) return;
    altKey = false;
    search.unpin();
    showHistory();
  };
  // Resolves once `text` has been typed into the live box, tentative word
  // included, so a move can land on the word that names it.
  const saidYet = async (text) => {
    while (!(out.textContent + live.textContent).includes(text)) await step(30);
  };
  async function epilogue(at) {
    if (!search) return;
    await both(say(EPILOGUE[0], at, at), (async () => {
      await saidYet('⌥');
      altKey = true;
      showHistory();
    })());
    await both(say(EPILOGUE[1], at, at), (async () => {
      await saidYet('⌥F');
      search.focus();
      await step(600);
      for (const ch of 'meeting') { search.type(ch); await step(150); }
    })());
    // Let go: the field empties and the stack fades under the line that
    // follows, the podcast's last.
    endEpilogue();
  }

  async function loop() {
    let index = 0;
    // Set by a jump, cleared by the scene that answers it: the switch that gets
    // there runs on its own rather than under the first caption.
    let picked = false;

    for (;;) {
      const scene = SCENES[index];
      const slice = 1 / scene.lines.length;
      const deliberate = picked;
      picked = false;

      paintScene(index);
      // Back to empty before the first caption of the scene, and instantly: the
      // wrap-around switch runs before any caption does, and the bar would
      // otherwise sit full through it.
      progress(0, 0);

      try {
        // Against what is actually in front, not against what the last switch
        // meant to leave there: an interrupted one may have fronted its window
        // already, and this scene's may be it.
        if (scene.app !== frontApp) {
          if (index === 0 || deliberate) {
            // Coming back round to the top, or somebody picked this scene. The
            // switch runs on its own, with the captions starting after it lands,
            // so the loop reads as beginning again rather than as a first line
            // that started while the previous scene's window was still in front.
            // Every other switch stays concurrent, below, because that is the
            // point being made.
            await switchTo(scene.app);
            await say(scene.lines[0], 0, slice);
          } else {
            // Deliberately concurrent: the caption keeps running straight
            // through the app switch, which is the whole point being made.
            await both(say(scene.lines[0], 0, slice), switchTo(scene.app));
          }
        } else {
          await say(scene.lines[0], 0, slice);
        }

        for (let j = 1; j < scene.lines.length; j++) {
          // Before the last line of the last scene, so that line closes the
          // loop with the stack fading under it.
          if (EPILOGUE && index === SCENES.length - 1 && j === scene.lines.length - 1) {
            await epilogue(j * slice);
          }
          await say(scene.lines[j], j * slice, (j + 1) * slice);
        }

        index = (index + 1) % SCENES.length;
        // The recording is one turn of the loop, cut at the wrap, and the
        // stack it raises should be that turn's: with the epilogue on, the
        // boxes start again from nothing each time round, or the search
        // would light the same line once per turn the page had run.
        if (EPILOGUE && index === 0) past.length = 0;
      } catch (error) {
        if (error !== JUMPED) throw error;
        // A jump out of the epilogue leaves nothing raised behind it.
        if (EPILOGUE) endEpilogue();
        // Somebody picked a scene. Drop whatever was mid-sentence and let the
        // next turn of the loop get there, which is also what makes a second
        // click during a switch work: it lands here again. A window click has
        // already fronted its window, so the next turn finds nothing to switch
        // and goes straight to the captions.
        index = jump.index;
        picked = !jump.direct;
        jump = null;
        switcher.classList.remove('is-visible');
        box.classList.remove('is-visible');
        out.textContent = '';
        live.textContent = '';
        progress(0, 0);
      }
    }
  }

  // ── the scene bar ─────────────────────────────────────────────────────────
  //
  // One segment per scene: how far through the loop is, and a way out of waiting
  // for it. Each one jumps to the top of its scene; the one already playing does
  // nothing, because restarting it would punish a click on the thing you are
  // already watching.

  const sceneButtons = [...document.querySelectorAll('.demo-scenes .scene-button')];
  const sceneFills = sceneButtons.map((b) => b.querySelector('.scene-fill'));
  let sceneIndex = 0;

  const paintScene = (index) => {
    // A window you are holding stops being yours when the demo moves on: the
    // loop reaches the next scene, brings another window forward, and the one
    // under the cursor is now behind it. The scene the drag itself asked for
    // does not count, which is what the app check is for.
    if (windowGrab && SCENES[index].app !== windowGrab.win.dataset.app) {
      endWindowDrag();
    }
    sceneIndex = index;
    sceneButtons.forEach((button, i) =>
      button.setAttribute('aria-current', i === index ? 'true' : 'false')
    );
  };

  // The loop hands the bar a target and a duration per caption, and CSS walks it
  // there, rather than the script animating a number frame by frame.
  const progress = (value, ms) => {
    sceneFills.forEach((fill, i) => {
      const to = i < sceneIndex ? 1 : i === sceneIndex ? value : 0;
      fill.style.transitionDuration = (i === sceneIndex ? ms : 0) + 'ms';
      fill.style.transform = 'scaleX(' + to + ')';
    });
  };

  // `direct` skips the ⌘-tab: clicking a window is reaching for that window.
  const jumpTo = (index, direct) => {
    if (index === sceneIndex || !SCENES[index]) return;
    jump = { index: index, direct: !!direct };
    paintScene(index);
    box.classList.remove('is-visible');
    progress(0, 0);
    if (direct) {
      front(SCENES[index].app);
      switcher.classList.remove('is-visible');
    }
    // Waking the loop is what makes this instant: it is otherwise sitting in
    // whatever wait it started before the click.
    wake();
  };

  sceneButtons.forEach((button, index) =>
    button.addEventListener('click', () => jumpTo(index, false))
  );

  const sceneOf = (app) => SCENES.findIndex((scene) => scene.app === app);
  windows.forEach((win) =>
    win.addEventListener('click', () => jumpTo(sceneOf(win.dataset.app), true))
  );

  // ── moving the windows ────────────────────────────────────────────────────
  //
  // By the title bar, as on a real desktop, and no modifier: the window comes
  // forward as you take hold of it. Sideways and downwards it can go where it
  // likes and be clipped by the screen; upwards it stops at the top of the
  // stage, which is the underside of the menu bar. Mouse only — on a phone the
  // title bar is inside a page you are trying to scroll.
  //
  // A dragged window is placed in fractions of the screen rather than by the
  // insets it started with, so it keeps its size and its spot at any width.

  const stage = document.querySelector('.demo-stage');
  let windowGrab = null;

  const endWindowDrag = () => {
    if (!windowGrab) return;
    const { handle, pointerId, win } = windowGrab;
    if (handle.hasPointerCapture(pointerId)) handle.releasePointerCapture(pointerId);
    win.classList.remove('is-held');
    windowGrab = null;
  };

  windows.forEach((win) => {
    const handle = win.querySelector('.win-titlebar');
    if (!handle || !stage) return;

    handle.addEventListener('pointerdown', (event) => {
      if (event.pointerType !== 'mouse') return;
      event.preventDefault();
      try { handle.setPointerCapture(event.pointerId); } catch (e) { /* pointer gone */ }

      const bounds = stage.getBoundingClientRect();
      const box2 = win.getBoundingClientRect();
      windowGrab = {
        win: win,
        handle: handle,
        pointerId: event.pointerId,
        width: box2.width / bounds.width,
        height: box2.height / bounds.height,
        x: (event.clientX - box2.left) / bounds.width,
        y: (event.clientY - box2.top) / bounds.height,
      };
      win.classList.add('is-held');
      win.style.inset = 'auto';
      // The position below is absolute; a margin the window was centred with
      // would move it by that much the moment it is picked up.
      win.style.marginInline = '0';
      win.style.width = (windowGrab.width * 100) + '%';
      win.style.height = (windowGrab.height * 100) + '%';
      win.style.left = ((box2.left - bounds.left) / bounds.width * 100) + '%';
      win.style.top = ((box2.top - bounds.top) / bounds.height * 100) + '%';
      // Taking hold of a window raises it, which here means playing its scene.
      jumpTo(sceneOf(win.dataset.app), true);
    });

    handle.addEventListener('pointermove', (event) => {
      if (!windowGrab || windowGrab.win !== win) return;
      const bounds = stage.getBoundingClientRect();
      const left = (event.clientX - bounds.left) / bounds.width - windowGrab.x;
      const top = (event.clientY - bounds.top) / bounds.height - windowGrab.y;
      win.style.left = (left * 100) + '%';
      win.style.top = (Math.max(0, top) * 100) + '%';
    });

    ['pointerup', 'pointercancel', 'lostpointercapture'].forEach((type) =>
      handle.addEventListener(type, endWindowDrag)
    );
  });

  // ── moving the caption box ────────────────────────────────────────────────
  //
  // The app lets the overlay through clicks until you hold shift, at which point
  // it becomes something you can pick up and put somewhere else. This does the
  // same, inside the fake screen, and it cannot be dropped outside it: the box
  // is the thing being demonstrated.

  let boxGrab = null;

  const insideStage = (x, y) => {
    if (!stage) return { x: x, y: y };
    const bounds = stage.getBoundingClientRect();
    const rect = box.getBoundingClientRect();
    const halfWide = rect.width / 2 / bounds.width;
    const halfTall = rect.height / 2 / bounds.height;
    return {
      x: Math.min(Math.max(x, halfWide), 1 - halfWide),
      y: Math.min(Math.max(y, halfTall), 1 - halfTall),
    };
  };

  const placeBox = (at) => {
    box.style.bottom = 'auto';
    box.style.left = (at.x * 100) + '%';
    box.style.top = (at.y * 100) + '%';
    box.style.transform = 'translate(-50%, -50%)';
  };

  // Tabbing away with the key down would otherwise leave it armed forever.
  const armBox = (on) => box.classList.toggle('is-movable', on);
  window.addEventListener('keydown', (e) => { if (e.key === 'Shift') armBox(true); });
  window.addEventListener('keyup', (e) => { if (e.key === 'Shift') armBox(false); });
  window.addEventListener('blur', () => armBox(false));

  box.addEventListener('pointerdown', (event) => {
    if (event.pointerType !== 'mouse' || !event.shiftKey || !stage) return;
    event.preventDefault();
    try { box.setPointerCapture(event.pointerId); } catch (e) { /* pointer gone */ }

    const bounds = stage.getBoundingClientRect();
    const rect = box.getBoundingClientRect();
    const centre = {
      x: (rect.left + rect.width / 2 - bounds.left) / bounds.width,
      y: (rect.top + rect.height / 2 - bounds.top) / bounds.height,
    };
    boxGrab = {
      pointerId: event.pointerId,
      x: centre.x - (event.clientX - bounds.left) / bounds.width,
      y: centre.y - (event.clientY - bounds.top) / bounds.height,
    };
    box.classList.add('is-dragging');
    placeBox(insideStage(centre.x, centre.y));
  });

  box.addEventListener('pointermove', (event) => {
    if (!boxGrab || !stage) return;
    const bounds = stage.getBoundingClientRect();
    placeBox(insideStage(
      (event.clientX - bounds.left) / bounds.width + boxGrab.x,
      (event.clientY - bounds.top) / bounds.height + boxGrab.y
    ));
  });

  ['pointerup', 'pointercancel', 'lostpointercapture'].forEach((type) =>
    box.addEventListener(type, () => {
      boxGrab = null;
      box.classList.remove('is-dragging');
    })
  );

  // ── the pointer reveal and the ⌥ stack ────────────────────────────────────
  //
  // Neither of these is drawn. The page has a pointer and something underneath
  // the captions, which is everything the reveal needs, and a keyboard with the
  // same modifier on it, so both are wired to the real thing and behave as they
  // do in the app. The geometry is in styles.css, against the app's own
  // constants; what is here is where the hole is and what is in the stack.

  const history = document.getElementById('caption-history');
  const screen = document.querySelector('.demo-screen');

  // The search pill at the stack's edge, as on the landing pages: pinned, the
  // stack stays up with ⌥ released; each keystroke repaints it narrowed and
  // parked on the newest match; unpinned, it answers to ⌥ again, and if it
  // stays up the boxes the search had hidden come back.
  const search = history && stackSearch.attach({
    history: history,
    onPin: () => showHistory(),
    onQuery: () => paintHistory(true),
    onUnpin: (hadQuery) => {
      showHistory();
      // Up still: every box back. Going: the field closes back down to its
      // pill as the stack fades, the boxes left as the search had them.
      if (!history.classList.contains('is-visible')) search.layout(history.offsetWidth, true);
      else if (hadQuery) paintHistory(true);
    },
  });
  const follow = history && stackSearch.follow(history, search);
  let altKey = false;

  // Closed pages, oldest first, at what was the app's `defaultHistoryDepth`
  // until 1.4.0, where the default became every box. The demo keeps the cap:
  // it speaks seven lines on a loop, and a stack of every repetition since the
  // page was opened would be hundreds of the same sentence.
  //
  // Held back to six at first, on the reasoning that this stage is only a few
  // hundred pixels tall and would clip most of them. That was the wrong way
  // round: a stack that always fits is a stack the scroll never does anything
  // to, and scrolling back through the older ones is half of what the feature
  // is. Fifteen overflows this stage comfortably, which is the point.
  //
  // The demo speaks seven distinct lines, so a full buffer repeats them. The
  // app would do the same with a speaker who repeats themselves: closePage only
  // refuses a line identical to the one before it.
  const PAST_MAX = 15;
  const past = [];

  // Pages carry an id rather than being matched on their text. The demo speaks
  // seven lines into fifteen slots, so the same sentence is in the stack more
  // than once, and keying the reconciliation below on text made two different
  // boxes look like one box that had moved. Everything downstream then rebuilt
  // and re-animated the lot.
  let pageId = 0;

  // Deduplicated against the last entry, as the app's own closePage is: a page
  // can close twice in a beat, and two identical boxes read as a stutter rather
  // than as history.
  const closePage = (line) => {
    const trimmed = line.trim();
    const last = past[past.length - 1];
    if (!trimmed || (last && trimmed === last.text)) return;
    past.push({ id: ++pageId, text: trimmed });
    if (past.length > PAST_MAX) past.splice(0, past.length - PAST_MAX);
    // A stack already up takes the box in. One that is not may be wanted
    // anyway: ⌥ pressed before anything had closed, and still held, which the
    // app's poll answers the moment a first page does.
    if (history && history.classList.contains('is-visible')) paintHistory();
    else showHistory();
  };

  // The live box's top edge, as the stack should hang off it.
  //
  // Between pages the box is invisible but still holds the caption that just
  // ended, at whatever height that sentence needed. Anchoring to that edge put
  // the stack where a two-line box had left it and then dropped it the moment
  // the next caption came up one line short, which reads as the stack lagging a
  // page behind.
  //
  // The box is bottom-anchored and grows upwards, so its bottom edge is the
  // stable one. While it is down, anchor to where a single line would put the
  // top instead, which is where the next caption opens. A sentence that goes on
  // to wrap still lifts the stack when it wraps, exactly as it does in the app.
  const anchorTop = (rect) => {
    if (box.classList.contains('is-visible')) return rect.top;
    const cs = getComputedStyle(box);
    const line = parseFloat(cs.lineHeight) || parseFloat(cs.fontSize) * 1.34;
    const oneLine = line + parseFloat(cs.paddingTop) + parseFloat(cs.paddingBottom);
    return Math.max(rect.top, rect.bottom - oneLine);
  };

  // Vertical space for the stack on one side of the live box. The gap is the
  // app's 6pt and the margin off the edge of the screen its 12pt, both at 30pt
  // of text, so both in em. The bottom edge needs no such care: it does not move
  // when the caption changes length.
  const roomFor = (above, rect, bounds, em) =>
    (above ? anchorTop(rect) - bounds.top : bounds.bottom - rect.bottom) - em * 0.6;

  // Which side of the live box the stack takes. Decided on the press that raises
  // it and held for as long as it is up: re-deciding it as the box resizes would
  // let one sentence wrapping to a second line throw the stack across it
  // mid-read, which is the app's reasoning too.
  let placedAbove = true;

  // Below this there is not enough room to be worth drawing: the app's 40pt.
  const MIN_ROOM = 1.33;

  // How tall the stack's content is, measured from layout rather than read off
  // `scrollHeight`.
  //
  // A box mid-entrance carries a transform, and a transformed child widens its
  // scroll container's scrollable overflow. So during the rise `scrollHeight`
  // reports a stack up to 0.4em taller than the one that will be standing there
  // a fifth of a second later. Parking the scroll against that number scrolled
  // the content up by those few pixels, and when the transforms resolved the
  // overflow shrank back and the browser clamped the scroll down again: the
  // boxes appeared slightly high and then dropped onto their real position.
  // Nothing engine-specific about it, which is why it happened everywhere.
  //
  // `offsetHeight` is layout and ignores transforms, so this is the height the
  // stack will settle at, available before it gets there.
  const contentHeight = () => {
    const kids = [...history.children];
    if (!kids.length) return 0;
    const gap = parseFloat(getComputedStyle(history).rowGap) || 0;
    return kids.reduce((sum, el) => sum + el.offsetHeight, 0) + gap * (kids.length - 1);
  };

  // How many boxes are still playing their entrance. While any of them is, the
  // scroll geometry below is not to be trusted or written to: a box mid-rise is
  // displaced by its own transform, and that displacement widens the scrollable
  // overflow it is measured against.
  let rising = 0;

  // The exact scroll range, from the browser rather than from arithmetic.
  //
  // This used to sum the children's `offsetHeight`, chosen because offsetHeight
  // is layout and ignores transforms. What it also is, is rounded to whole
  // pixels: the pills are fractional tall, so the error compounded down the
  // stack and a full one was off by several pixels. Parking against that number
  // put the scroll past the real end, the browser clamped it back, and the stack
  // snapped — which is why it only appeared once the history filled up.
  //
  // scrollHeight is exact and fractional. It is only wrong while a transform is
  // in flight, and `rising` is what keeps this from being read then.
  const maxScroll = () => Math.max(0, history.scrollHeight - history.clientHeight);

  // Distance between the edge nearest the live box and the end of the content
  // on that side. Zero means the newest box is flush against the live one,
  // which is where the stack parks itself. Everything is measured from that
  // edge because it is the one the reader is anchored to and the end new boxes
  // arrive at — and which edge that is depends on the side the stack took.
  const nearDistance = () =>
    placedAbove ? maxScroll() - history.scrollTop : history.scrollTop;

  // When the reader last turned the wheel, and when we last moved the scroll
  // ourselves. The second exists only to keep the first honest: every write
  // below fires a scroll event, and without telling them apart the stack would
  // read its own corrections as a gesture.
  let userScrolledAt = -1e9;
  let selfScrolledAt = -1e9;

  // Whether the stack is sitting against the live box, tracked rather than
  // measured. Deriving it from the scroll offset meant reading geometry at the
  // one moment it cannot be trusted: a box closing while an earlier one is still
  // rising would have read as the reader having scrolled away, and the stack
  // would have refused to follow the newest box.
  let parked = true;

  const setNearDistance = (distance) => {
    const max = maxScroll();
    const clamped = Math.min(Math.max(distance, 0), max);
    selfScrolledAt = performance.now();
    history.scrollTop = placedAbove ? max - clamped : clamped;
  };

  // Fade the edge that still has boxes beyond it, and only that one.
  //
  // The far edge, never the near one: the box against the live one is the
  // newest and the one being read, so dimming it would be backwards.
  //
  // And only while something is genuinely hidden there. Scroll to the end and
  // the fade goes with it, because a fade with nothing behind it advertises
  // content that is not there. The band is sized to the amount actually hidden,
  // so a stack overflowing by ten pixels gets a ten-pixel fade rather than
  // swallowing a whole box to announce it, and it never takes more than half
  // the visible height.
  const FADE_MAX = 2.2;

  // Only the depth moves. `is-clipped` is deliberately left alone here and set
  // from layout in placeHistory instead: it carries the mask, and adding or
  // removing a mask on a scroll container disturbs the scroll, so toggling it
  // on every scroll frame put the fade in a fight with the gesture it was
  // reading. A depth of zero looks exactly like no mask and costs the scroller
  // nothing.
  const updateFade = () => {
    if (!history) return;
    const em = parseFloat(getComputedStyle(history).fontSize) || 16;
    const hidden = Math.max(0, maxScroll() - nearDistance());
    const fade = Math.min(em * FADE_MAX, hidden, history.clientHeight / 2);
    history.style.setProperty('--fade', fade.toFixed(1) + 'px');
  };

  // Follows the wheel, not just the moment the stack is built: scrolling is
  // exactly when the amount hidden at each edge changes. One update a frame,
  // because this writes a property and then measures, and doing that on every
  // scroll event is how a handler starts costing more than the scroll.
  let fadeQueued = false;
  if (history) history.addEventListener('scroll', () => {
    if (performance.now() - selfScrolledAt > 60) {
      userScrolledAt = performance.now();
      // Only worth reading between entrances, when the geometry is honest.
      if (!rising) parked = nearDistance() < 1;
    }
    if (fadeQueued) return;
    fadeQueued = true;
    requestAnimationFrame(() => { fadeQueued = false; updateFade(); });
  });

  // Pinned to the live box, so dragging the captions takes the stack with them.
  //
  // Deliberately does not park the scroll. This runs on every frame the stack
  // is up, to follow a live box that moves and resizes under it, and parking
  // here is what threw the reader back to the newest box the instant they
  // scrolled away from it.
  const placeHistory = () => {
    if (!history || !stage) return;
    const bounds = stage.getBoundingClientRect();
    const rect = box.getBoundingClientRect();
    const em = parseFloat(getComputedStyle(history).fontSize) || 16;
    const room = roomFor(placedAbove, rect, bounds, em);
    const near = nearDistance();
    const was = history.clientHeight;
    // The search pill sits at the near edge, a gap off the live box, and the
    // boxes beyond it, so it comes off the room before they are measured
    // against it, as the app's does.
    const block = search.height() + em * 0.2;
    const content = contentHeight();

    // Rounded, because `room` is derived from the live box's rect and jitters by
    // fractions of a pixel as a caption is typed. Left as a float it crossed the
    // half-pixel test below on its own every few frames, and every crossing was
    // a scroll correction the reader had not asked for.
    history.style.maxHeight = Math.max(0, Math.round(room - block)) + 'px';

    // Nowhere left to put it. Hidden rather than emptied, because the live box
    // shrinks again on the next page and the stack should still be there. A
    // stack with nothing in it, every box filtered out, still shows the field,
    // and needs only the field's own height.
    const starved = room < (content > 0 ? em * MIN_ROOM + block : search.height());
    history.classList.toggle('is-starved', starved);
    search.setStarved(starved);
    // Sprung after the live box while the stack is up, straight there when it
    // is arriving, as the app's is.
    const edge = placedAbove ? bounds.bottom - anchorTop(rect) : rect.bottom - bounds.top;
    follow(rect.left + rect.width / 2 - bounds.left, edge + em * 0.2, placedAbove, block,
           history.classList.contains('is-visible') && !starved);
    // Whether the stack can scroll at all, which changes only when a box lands
    // or the live box takes room away — never mid-gesture.
    history.classList.toggle('is-clipped', content > room - block + 1);
    search.layout(history.offsetWidth, history.classList.contains('is-visible'));

    // Only a change of height disturbs the scroller; the live box merely moving
    // does not. Put the reader back the same distance from the live box, so a
    // box growing to a second line eats the stack from the far end rather than
    // sliding it under them.
    // Never mid-gesture. Someone flicking through the stack while a caption
    // happens to resize the live box underneath is navigating, and moving the
    // content under them is the one thing that must not happen — the app draws
    // the same line with `!scroll.isScrolling`.
    if (Math.abs(history.clientHeight - was) > 0.5
        && performance.now() - userScrolledAt > 400
        && !rising) setNearDistance(near);

    updateFade();
  };

  // Reconciled rather than rebuilt, so that a box already on screen is not
  // animated again when a page closes while ⌥ is still held — only the one that
  // just closed rises. The app does the same, against the same problem.
  // `park` forces the scroll to the newest box: the search asks for that on
  // every keystroke, where a page closing leaves the reader where they were.
  const paintHistory = (park) => {
    if (!history) return;
    const fresh = !history.classList.contains('is-visible');
    // Read the reader's place before the rebuild destroys it. Sticking to the
    // newest box is right only if that is where they already were; if they had
    // scrolled back to an older one, hold *that* box still instead. New text
    // arriving must not drag the page out from under someone mid-sentence.
    const wasParked = fresh || !history.children.length || parked;
    const wasNear = nearDistance();
    const wasContent = contentHeight();

    // Reversed when the stack hangs below, so the newest box is the one touching
    // the live box either way.
    const ordered = placedAbove ? past : [...past].reverse();

    // Patched in place. The boxes already standing are never detached, only the
    // ones that have fallen out of the buffer are removed and the new one is
    // inserted where it belongs.
    //
    // The previous version emptied the container and re-appended the survivors,
    // which is what re-ran the entrance on the whole stack: taking an element
    // out of the document and putting it back restarts a CSS animation that is
    // still named on it. Leaving them alone also leaves the scroll position
    // alone, which the browser maintains for as long as the boxes it is
    // measured against stay put.
    const living = new Set(ordered.map((page) => String(page.id)));
    [...history.children].forEach((el) => {
      if (!living.has(el.dataset.pid)) el.remove();
    });

    const risen = [];
    ordered.forEach((page, i) => {
      const here = history.children[i];
      if (here && here.dataset.pid === String(page.id)) return;
      const el = document.createElement('div');
      el.className = 'hist-line';
      el.dataset.pid = page.id;
      history.insertBefore(el, here || null);
      risen.push(el);
    });

    // Every box counts towards the width, filtered out or not: a stack that
    // narrowed as the query did would jitter under each keystroke, and the
    // search pill takes its width from the stack's. So the width is read with
    // every box standing, then held while the search hides some. Hidden rather
    // than removed: a box keeps its place for when the query changes.
    const kids = [...history.children];
    const pageOf = (el) => past.find((p) => String(p.id) === el.dataset.pid);
    history.style.minWidth = '';
    kids.forEach((el) => {
      const page = pageOf(el);
      if (page) search.write(el, page.text);
      el.classList.remove('is-hidden');
    });
    history.style.minWidth = history.offsetWidth + 'px';
    kids.forEach((el) => {
      const page = pageOf(el);
      if (page) el.classList.toggle('is-hidden', !search.matches(page.text));
    });

    placeHistory();

    // Settle the scroll while the new boxes are still sitting at their resting
    // position, before a single transform exists to widen the overflow they are
    // measured against. Parked stays parked; otherwise the box they were reading
    // holds still, which means moving with the growth that landed at the near
    // end.
    setNearDistance(park || wasParked ? 0 : wasNear + (contentHeight() - wasContent));
    parked = park || wasParked;

    // Only now do they animate. Nearest the live box first, so the stack unrolls
    // out of it: the newest box is last above the live one and first below. The
    // pill goes before them all when the stack is opening. A box the search
    // hides does not rise: it has nowhere to be seen, and an entrance that never
    // ends would hold the scroll geometry hostage.
    if (fresh) search.rise();
    risen.forEach((el) => {
      if (el.classList.contains('is-hidden')) return;
      const i = kids.indexOf(el);
      el.style.setProperty('--rise', (placedAbove ? kids.length - 1 - i : i) + (fresh ? 1 : 0));
      rising++;
      el.addEventListener('animationend', () => { rising = Math.max(0, rising - 1); },
                          { once: true });
      el.classList.add('is-rising');
    });
  };

  // Up while ⌥ is held, or while the search has it pinned, when it stays up
  // whatever the modifier keys are doing.
  const showHistory = () => {
    if (!history || !stage) return;
    const want = (altKey || search.pinned) && past.length > 0;

    if (want) {
      // A fresh press builds the stack from nothing, so every box rises. Only
      // while ⌥ is still held does the reconciliation in paintHistory matter,
      // and then it is a single box that just closed, joining a stack that is
      // already up. The app draws the same line.
      if (!history.classList.contains('is-visible')) {
        history.textContent = '';
        // Whatever was still animating went with them, and a fresh press always
        // opens against the live box.
        rising = 0;
        parked = true;

        // Flip only when there is genuinely more room the other way, which is
        // what makes the stack fall below the box once the box is dragged to
        // the top. Decided once, on the press that raises it, and held for as
        // long as it is up: re-deciding it as the box resizes would let one
        // sentence wrapping to a second line throw the stack across it
        // mid-read, which is the app's reasoning too.
        const bounds = stage.getBoundingClientRect();
        const rect = box.getBoundingClientRect();
        const em = parseFloat(getComputedStyle(history).fontSize) || 16;
        placedAbove = roomFor(true, rect, bounds, em) >= roomFor(false, rect, bounds, em);
        history.classList.toggle('is-below', !placedAbove);
        search.setBelow(!placedAbove);
      }
      paintHistory();
    }
    // The boxes are left in place on the way out so the stack fades rather than
    // vanishing; the next press is what clears them.
    history.classList.toggle('is-visible', want);
    search.setVisible(want);
    box.classList.toggle('is-solid', want);
    queueHole();
  };

  // Where the pointer is, in the page's coordinates. Kept rather than the hole's
  // offset because the box moves under a still pointer far more than the pointer
  // moves over a still box: it re-centres and re-sizes on every word, and the
  // app recomputes the centre on exactly the same events for the same reason.
  let pointer = null;
  let holeQueued = false;

  const paintHole = () => {
    // ⇧ keeps the box solid, the way it does in the app: you are about to pick
    // it up, and a hole under the hand you are picking it up with is no help.
    // ⌥ does too, because the stack is what is being read then.
    if (!pointer || box.classList.contains('is-movable') || box.classList.contains('is-solid')) {
      box.style.setProperty('--hole-x', '-999px');
      box.style.setProperty('--hole-y', '-999px');
      return;
    }
    const rect = box.getBoundingClientRect();
    box.style.setProperty('--hole-x', (pointer.x - rect.left) + 'px');
    box.style.setProperty('--hole-y', (pointer.y - rect.top) + 'px');
  };

  // One paint a frame at most. The box resizes on every word and the pointer
  // reports faster than that, so both feed the same queue.
  const queueHole = () => {
    if (holeQueued) return;
    holeQueued = true;
    requestAnimationFrame(() => {
      holeQueued = false;
      paintHole();
      if (history && history.classList.contains('is-visible')) placeHistory();
    });
  };

  if (screen) {
    screen.addEventListener('pointermove', (event) => {
      if (event.pointerType !== 'mouse') return;
      pointer = { x: event.clientX, y: event.clientY };
      queueHole();
    });
    // Nothing to turn off: the falloff means distance alone ends the reveal, on
    // this screen as on a real one. This is only for the pointer that leaves in
    // one jump, or out of the window entirely.
    screen.addEventListener('pointerleave', () => { pointer = null; queueHole(); });
  }

  // The box changes width on almost every word, which moves its left edge by
  // most of the box. Without this the hole lands off the pointer until the
  // pointer next moves, and reads as the reveal blinking out.
  if (typeof ResizeObserver === 'function') new ResizeObserver(queueHole).observe(box);

  // Tabbing away with either key down would otherwise leave it armed forever,
  // the same reason armBox watches blur.
  window.addEventListener('keydown', (e) => {
    // Held keys repeat, and a repeat that repainted would restart the stagger
    // over and over for as long as ⌥ is down.
    if (e.key === 'Alt' && !e.repeat) { altKey = true; showHistory(); }
    if (e.key === 'Shift') queueHole();
  });
  window.addEventListener('keyup', (e) => {
    if (e.key === 'Alt') { altKey = false; showHistory(); }
    if (e.key === 'Shift') queueHole();
  });
  window.addEventListener('blur', () => { altKey = false; showHistory(); });

  // Only run while the demo is actually on screen...
  new IntersectionObserver(
    ([entry]) => { onScreen = entry.isIntersecting; sync(); },
    { threshold: 0.15 }
  ).observe(box);

  // ...and only while the tab is in front: timers in a backgrounded tab are
  // throttled to about one a second, which would wreck the pacing.
  document.addEventListener('visibilitychange', sync);

  loop();
})();
