// Generated by tools/vendor-demo.sh from the site's script.js. Do not edit.
// Copy that this script writes into the page lives in <template id="i18n-js">,
// so it can be extracted and translated like any markup string. The literals
// passed here are the English fallback, used when the template is absent.
const I18N = (() => {
  const tpl = document.getElementById('i18n-js');
  const map = {};
  if (tpl) {
    for (const el of tpl.content.querySelectorAll('[data-js]')) {
      map[el.dataset.js] = el.textContent.trim();
    }
  }
  return (name, fallback) => map[name] || fallback;
})();

(function menuBarClock() {
  const el = document.getElementById('mb-time');
  if (!el) return;

  // macOS shows weekday, date and time in the user's own locale.
  const fmt = new Intl.DateTimeFormat(navigator.language || 'en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    hour: 'numeric',
    minute: '2-digit',
  });

  let timer;
  const tick = () => {
    el.textContent = fmt.format(new Date());
    // Re-arm on the next minute boundary rather than polling every second.
    clearTimeout(timer);
    timer = setTimeout(tick, 60000 - (Date.now() % 60000) + 50);
  };

  tick();
  // A backgrounded tab throttles timers, so resync when it comes back.
  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) tick();
  });
})();

(function captionDemo() {
  const box = document.getElementById('caption-box');
  const out = document.getElementById('caption-text');
  const live = document.getElementById('caption-live');
  const glyph = document.getElementById('mb-glyph');
  const switcher = document.getElementById('switcher');
  const windows = document.querySelectorAll('.demo-window');
  if (!box || !out) return;

  const APPS = {
    meeting: I18N('app.meeting', 'Meetings'),
    notes: I18N('app.notes', 'Notes'),
    player: I18N('app.player', 'Player'),
  };

  // Every icon carries its own name, and only the selected one shows it. That is
  // what makes the label move with the selection, and it is why the panel's
  // width is the icons' business alone: the label is out of flow, so a long app
  // name cannot stretch the thing it is labelling.
  windows.length && switcher.querySelectorAll('.sw-app').forEach((el) => {
    const label = el.querySelector('.sw-name');
    if (label) label.textContent = APPS[el.dataset.app];
  });

  // The transport runs only while the player is the window in front, and runs
  // faster than real time on purpose: a scene lasts about a dozen seconds, and a
  // real playhead would not visibly move in that. The clock counting up is the
  // part people read as "this is playing", so that is the part that has to move.
  const CALM = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // Who is talking, handed round the tiles the way it goes in a real call:
  // never straight back to the same person, and held for an uneven beat,
  // because a fixed rotation reads as a carousel rather than a conversation.
  const speakers = (() => {
    const tiles = [...document.querySelectorAll('.win-meeting .tile')];
    let timer = null;
    let at = 0;
    const hand = (to) => {
      at = to;
      tiles.forEach((t, i) => t.classList.toggle('is-speaking', i === at));
    };
    const step = () => {
      hand((at + 1 + Math.floor(Math.random() * (tiles.length - 1))) % tiles.length);
      timer = setTimeout(step, 2100 + Math.random() * 1700);
    };
    let running = false;
    return (on) => {
      // Only on the change. This is called on every switch now, not just when
      // the call fronts, and re-running it while the call was already talking
      // handed the ring back to the first tile each time.
      if (on === running) return;
      running = on;
      clearTimeout(timer);
      // Stopping used to mean stopping the hand-off and nothing else, which left
      // whoever was talking wearing the ring. On a stack that did not matter,
      // because the call was behind one window and barely visible; fanned out it
      // is a third of the screen, and a ring pulsing away under the podcast said
      // a meeting was live in a scene about a podcast. Put the tiles back to
      // nobody speaking, and the window goes quiet with the scene.
      if (!on || !tiles.length) {
        tiles.forEach((t) => t.classList.remove('is-speaking'));
        return;
      }
      // Somebody is talking the moment the call is in front. Reduced motion gets
      // that as a still ring: it is who is speaking, not an animation.
      hand(0);
      if (CALM) return;
      timer = setTimeout(step, 1900);
    };
  })();

  const playhead = (() => {
    const fill = document.getElementById('pod-fill');
    const clock = document.getElementById('pod-elapsed');
    const bars = [...document.querySelectorAll('#pod-wave i')];
    const START = 18 * 60 + 24;   // 18:24, where the markup starts
    const TOTAL = 41 * 60 + 7;    // 41:07
    const RATE = 4;               // seconds of episode per second of demo
    let timer = null;
    let at = START;

    const mmss = (s) =>
      Math.floor(s / 60) + ':' + String(Math.floor(s % 60)).padStart(2, '0');

    const paint = () => {
      const pct = at / TOTAL;
      if (fill) fill.style.width = (pct * 100).toFixed(2) + '%';
      if (clock) clock.textContent = mmss(at);
      const played = Math.round(pct * bars.length);
      bars.forEach((b, i) => b.classList.toggle('is-played', i < played));
    };

    let running = false;
    return (on) => {
      if (!bars.length || CALM) return;
      // Only on the change, for the same reason as the speakers above: the
      // episode now runs on behind the notes, and restarting it every time
      // something else fronted pinned the clock to 18:24.
      if (on === running) return;
      running = on;
      clearInterval(timer);
      if (!on) return;
      at = START;   // every time it starts playing again, it starts here
      paint();
      timer = setInterval(() => {
        // A backgrounded tab should not run the episode on without anybody
        // watching, or coming back to it shows a clock that has raced ahead.
        if (document.hidden) return;
        at = Math.min(TOTAL, at + RATE);
        paint();
      }, 1000);
    };
  })();

  // Which window is actually in front, updated the moment it fronts rather than
  // once a switch has finished: a switch interrupted by a second click has
  // already fronted its window, and a loop carrying that in a local of its own
  // would open the next ⌘-tab panel on the wrong app.
  let frontApp = 'meeting';

  // Back to front, and the only thing that decides what covers what. The three
  // windows used to share one z-index with the front one lifted above them, so
  // everything behind fell back on the order it happens to sit in the markup:
  // raising the notes also carried the podcast over the call, because the
  // podcast is written last. A desktop does not work that way. Whatever you
  // raise goes on top and the rest keep the order they were already in, so the
  // stack is a record of what you have looked at, however you got there: the
  // scene loop, the buttons under it, a click on a window, or a drag by its
  // title bar all arrive here.
  const stack = ['notes', 'player', 'meeting'];
  // Two of the three windows make a sound, and the one higher in the stack is
  // the one making it: switching between them hands the sound over rather than
  // stopping it, and the notes never take it, so something is always playing.
  const playingApp = () =>
    stack.indexOf('meeting') > stack.indexOf('player') ? 'meeting' : 'player';

  const restack = (app) => {
    const at = stack.indexOf(app);
    if (at !== -1) stack.splice(at, 1);
    stack.push(app);
    const playing = playingApp();
    windows.forEach((w) => {
      // 1 to 3, well under the switcher at 6 and the caption at 10, both of
      // which are above every window by definition.
      w.style.setProperty('--z', stack.indexOf(w.dataset.app) + 1);
      w.classList.toggle('is-playing', w.dataset.app === playing);
    });
  };

  const front = (app) => {
    frontApp = app;
    restack(app);
    windows.forEach((w) => w.classList.toggle('is-front', w.dataset.app === app));
    // Both on the same rule as the class above, and neither on being in front:
    // fronting the notes leaves whichever was playing still playing behind them.
    playhead(playingApp() === 'player');
    speakers(playingApp() === 'meeting');
  };
  const select = (app) => {
    switcher.querySelectorAll('.sw-app').forEach((el) =>
      el.classList.toggle('is-selected', el.dataset.app === app)
    );
  };

  // Three scenes: the call, whatever you switch to while it keeps playing, and
  // the podcast. The captions are what the audio is saying.
  const SCENES = [
    {
      app: 'meeting',
      lines: [
        I18N('line.meeting1', 'Universal subtitles for any app, live on your Mac.'),
        I18N('line.meeting2', 'In a meeting, second language or not, one missed word costs you the next three.'),
        I18N('line.meeting3', 'So the captions run live, over the call, while people are still talking.'),
      ],
    },
    {
      app: 'notes',
      lines: [
        I18N('line.notes1', 'Switch to your notes and the meeting carries on without you watching it.'),
        I18N('line.notes2', 'The overlay stays above every window, so you keep the thread.'),
      ],
    },
    {
      app: 'player',
      lines: [
        I18N('line.player1', 'The same for a podcast, a lecture, or a video.'),
        I18N('line.player2', 'And none of it leaves the Mac: it runs on the Neural Engine, on-device.'),
      ],
    },
  ];

  front(SCENES[0].app);
  select(SCENES[0].app);
  if (glyph) glyph.classList.add('is-live');

  if (CALM) {
    // No loop to unwind — the scene is just what is on screen, so the bar places
    // it directly. The buttons are still worth having: they are the only way
    // through the three scenes when nothing is animating.
    out.textContent = SCENES[0].lines[0];
    box.classList.add('is-visible');
    [...document.querySelectorAll('.demo-scenes .scene-button')].forEach(
      (button, index) =>
        button.addEventListener('click', () => {
          front(SCENES[index].app);
          out.textContent = SCENES[index].lines[0];
          document
            .querySelectorAll('.demo-scenes .scene-button')
            .forEach((b, i) =>
              b.setAttribute('aria-current', i === index ? 'true' : 'false')
            );
        })
    );
    return;
  }

  const WORD_MS = 130;   // roughly conversational pace
  const JITTER = 80;
  const GAP_MS = 500;    // blank between boxes
  // A finished box holds long enough to actually be read: a base beat plus
  // time per word, so a long caption is not gone before you reach the end.
  const holdFor = (words) => Math.min(1500 + words * 130, 4200);

  // One loop for the lifetime of the page. It parks on `paused` instead of
  // returning, because restarting it on every scroll-back stacked a second
  // copy on top of the first and the two raced the caption text.
  let onScreen = true;
  let paused = false;
  const sync = () => { paused = !onScreen || document.hidden; };

  // Set by a click on a scene button or on one of the windows; the loop unwinds
  // at its next beat and picks that scene up from the top. `direct` is the
  // difference between the two: the buttons are a request to go somewhere, and
  // watching the ⌘-tab get there is the point of them, while clicking a window
  // is reaching for that window — the machinery in between would be in the way.
  let jump = null;
  const JUMPED = Symbol('jumped');

  // Every wait currently in flight, so a click can end them all now rather than
  // when their timer says so. Without it a click landed whenever the current
  // wait happened to end, and a caption that has finished typing holds for up to
  // 4.2 seconds — long enough to read as nothing having happened.
  const waking = new Set();
  const wait = (ms) => new Promise((resolve) => {
    const finish = () => { clearTimeout(timer); waking.delete(finish); resolve(); };
    const timer = setTimeout(finish, ms);
    waking.add(finish);
  });
  const wake = () => { [...waking].forEach((finish) => finish()); };

  async function step(ms) {
    await wait(ms);
    while (paused && !jump) await wait(150);
    if (jump) throw JUMPED;
  }

  // One subtitle box: types out, holds long enough to read, clears. The app
  // pages the same way, and shows the newest word dim until it commits.
  //
  // `from` and `to` are the slice of the scene's bar this caption is worth. The
  // bar is walked across it in two moves — one for the typing, one for the hold
  // — because those are the only two moments the loop knows how long the next
  // stretch will take. The second starts from wherever the first actually got
  // to, so the jitter in the typing corrects itself rather than piling up.
  async function say(line, from, to) {
    const words = line.split(' ');
    const hold = holdFor(words.length);
    const typing = words.length * (WORD_MS + JITTER / 2);
    const typed = from + (to - from) * (typing / (typing + hold + GAP_MS));

    out.textContent = '';
    live.textContent = '';
    box.classList.add('is-visible');
    progress(typed, typing);

    for (let i = 0; i < words.length; i++) {
      if (jump) throw JUMPED;
      out.textContent = i ? words.slice(0, i).join(' ') + ' ' : '';
      live.textContent = words[i];
      // A comma or full stop gets a beat, the way speech does.
      const punctuated = /[,.;:—]$/.test(words[i]);
      await step(WORD_MS + Math.random() * JITTER + (punctuated ? 180 : 0));
    }

    // Everything commits once the utterance ends.
    out.textContent = line;
    live.textContent = '';
    progress(to, hold + GAP_MS);

    await step(hold);
    box.classList.remove('is-visible');
    // The page has closed. The app records it here too, at the fade, because
    // fading is precisely when somebody looked away and will want it back.
    closePage(line);
    await step(GAP_MS);
  }

  // ⌘-tab: panel up on the current app, selection moves, window fronts as the
  // panel drops — which is when you'd release the key.
  async function switchTo(to) {
    select(frontApp);
    switcher.classList.add('is-visible');
    await step(340);
    select(to);
    await step(560);
    front(to);
    switcher.classList.remove('is-visible');
    await step(220);
  }

  // Both halves of a concurrent pair have to finish before the loop moves on,
  // including when one of them threw: awaiting Promise.all would leave the other
  // running against a loop that has already unwound, and its rejection
  // unhandled a beat later.
  async function both(a, b) {
    const settled = await Promise.allSettled([a, b]);
    const failed = settled.find((result) => result.status === 'rejected');
    if (failed) throw failed.reason;
  }

  async function loop() {
    let index = 0;
    // Set by a jump, cleared by the scene that answers it: the switch that gets
    // there runs on its own rather than under the first caption.
    let picked = false;

    for (;;) {
      const scene = SCENES[index];
      const slice = 1 / scene.lines.length;
      const deliberate = picked;
      picked = false;

      paintScene(index);
      // Back to empty before the first caption of the scene, and instantly: the
      // wrap-around switch runs before any caption does, and the bar would
      // otherwise sit full through it.
      progress(0, 0);

      try {
        // Against what is actually in front, not against what the last switch
        // meant to leave there: an interrupted one may have fronted its window
        // already, and this scene's may be it.
        if (scene.app !== frontApp) {
          if (index === 0 || deliberate) {
            // Coming back round to the top, or somebody picked this scene. The
            // switch runs on its own, with the captions starting after it lands,
            // so the loop reads as beginning again rather than as a first line
            // that started while the previous scene's window was still in front.
            // Every other switch stays concurrent, below, because that is the
            // point being made.
            await switchTo(scene.app);
            await say(scene.lines[0], 0, slice);
          } else {
            // Deliberately concurrent: the caption keeps running straight
            // through the app switch, which is the whole point being made.
            await both(say(scene.lines[0], 0, slice), switchTo(scene.app));
          }
        } else {
          await say(scene.lines[0], 0, slice);
        }

        for (let j = 1; j < scene.lines.length; j++) {
          await say(scene.lines[j], j * slice, (j + 1) * slice);
        }

        index = (index + 1) % SCENES.length;
      } catch (error) {
        if (error !== JUMPED) throw error;
        // Somebody picked a scene. Drop whatever was mid-sentence and let the
        // next turn of the loop get there, which is also what makes a second
        // click during a switch work: it lands here again. A window click has
        // already fronted its window, so the next turn finds nothing to switch
        // and goes straight to the captions.
        index = jump.index;
        picked = !jump.direct;
        jump = null;
        switcher.classList.remove('is-visible');
        box.classList.remove('is-visible');
        out.textContent = '';
        live.textContent = '';
        progress(0, 0);
      }
    }
  }

  // ── the scene bar ─────────────────────────────────────────────────────────
  //
  // One segment per scene: how far through the loop is, and a way out of waiting
  // for it. Each one jumps to the top of its scene; the one already playing does
  // nothing, because restarting it would punish a click on the thing you are
  // already watching.

  const sceneButtons = [...document.querySelectorAll('.demo-scenes .scene-button')];
  const sceneFills = sceneButtons.map((b) => b.querySelector('.scene-fill'));
  let sceneIndex = 0;

  const paintScene = (index) => {
    // A window you are holding stops being yours when the demo moves on: the
    // loop reaches the next scene, brings another window forward, and the one
    // under the cursor is now behind it. The scene the drag itself asked for
    // does not count, which is what the app check is for.
    if (windowGrab && SCENES[index].app !== windowGrab.win.dataset.app) {
      endWindowDrag();
    }
    sceneIndex = index;
    sceneButtons.forEach((button, i) =>
      button.setAttribute('aria-current', i === index ? 'true' : 'false')
    );
  };

  // The loop hands the bar a target and a duration per caption, and CSS walks it
  // there, rather than the script animating a number frame by frame.
  const progress = (value, ms) => {
    sceneFills.forEach((fill, i) => {
      const to = i < sceneIndex ? 1 : i === sceneIndex ? value : 0;
      fill.style.transitionDuration = (i === sceneIndex ? ms : 0) + 'ms';
      fill.style.transform = 'scaleX(' + to + ')';
    });
  };

  // `direct` skips the ⌘-tab: clicking a window is reaching for that window.
  const jumpTo = (index, direct) => {
    if (index === sceneIndex || !SCENES[index]) return;
    jump = { index: index, direct: !!direct };
    paintScene(index);
    box.classList.remove('is-visible');
    progress(0, 0);
    if (direct) {
      front(SCENES[index].app);
      switcher.classList.remove('is-visible');
    }
    // Waking the loop is what makes this instant: it is otherwise sitting in
    // whatever wait it started before the click.
    wake();
  };

  sceneButtons.forEach((button, index) =>
    button.addEventListener('click', () => jumpTo(index, false))
  );

  const sceneOf = (app) => SCENES.findIndex((scene) => scene.app === app);
  windows.forEach((win) =>
    win.addEventListener('click', () => jumpTo(sceneOf(win.dataset.app), true))
  );

  // ── moving the windows ────────────────────────────────────────────────────
  //
  // By the title bar, as on a real desktop, and no modifier: the window comes
  // forward as you take hold of it. Sideways and downwards it can go where it
  // likes and be clipped by the screen; upwards it stops at the top of the
  // stage, which is the underside of the menu bar. Mouse only — on a phone the
  // title bar is inside a page you are trying to scroll.
  //
  // A dragged window is placed in fractions of the screen rather than by the
  // insets it started with, so it keeps its size and its spot at any width.

  const stage = document.querySelector('.demo-stage');
  let windowGrab = null;

  const endWindowDrag = () => {
    if (!windowGrab) return;
    const { handle, pointerId, win } = windowGrab;
    if (handle.hasPointerCapture(pointerId)) handle.releasePointerCapture(pointerId);
    win.classList.remove('is-held');
    windowGrab = null;
  };

  windows.forEach((win) => {
    const handle = win.querySelector('.win-titlebar');
    if (!handle || !stage) return;

    handle.addEventListener('pointerdown', (event) => {
      if (event.pointerType !== 'mouse') return;
      event.preventDefault();
      try { handle.setPointerCapture(event.pointerId); } catch (e) { /* pointer gone */ }

      const bounds = stage.getBoundingClientRect();
      const box2 = win.getBoundingClientRect();
      windowGrab = {
        win: win,
        handle: handle,
        pointerId: event.pointerId,
        width: box2.width / bounds.width,
        height: box2.height / bounds.height,
        x: (event.clientX - box2.left) / bounds.width,
        y: (event.clientY - box2.top) / bounds.height,
      };
      win.classList.add('is-held');
      win.style.inset = 'auto';
      win.style.width = (windowGrab.width * 100) + '%';
      win.style.height = (windowGrab.height * 100) + '%';
      win.style.left = ((box2.left - bounds.left) / bounds.width * 100) + '%';
      win.style.top = ((box2.top - bounds.top) / bounds.height * 100) + '%';
      // Taking hold of a window raises it, which here means playing its scene.
      jumpTo(sceneOf(win.dataset.app), true);
    });

    handle.addEventListener('pointermove', (event) => {
      if (!windowGrab || windowGrab.win !== win) return;
      const bounds = stage.getBoundingClientRect();
      const left = (event.clientX - bounds.left) / bounds.width - windowGrab.x;
      const top = (event.clientY - bounds.top) / bounds.height - windowGrab.y;
      win.style.left = (left * 100) + '%';
      win.style.top = (Math.max(0, top) * 100) + '%';
    });

    ['pointerup', 'pointercancel', 'lostpointercapture'].forEach((type) =>
      handle.addEventListener(type, endWindowDrag)
    );
  });

  // ── moving the caption box ────────────────────────────────────────────────
  //
  // The app lets the overlay through clicks until you hold shift, at which point
  // it becomes something you can pick up and put somewhere else. This does the
  // same, inside the fake screen, and it cannot be dropped outside it: the box
  // is the thing being demonstrated.

  let boxGrab = null;

  const insideStage = (x, y) => {
    if (!stage) return { x: x, y: y };
    const bounds = stage.getBoundingClientRect();
    const rect = box.getBoundingClientRect();
    const halfWide = rect.width / 2 / bounds.width;
    const halfTall = rect.height / 2 / bounds.height;
    return {
      x: Math.min(Math.max(x, halfWide), 1 - halfWide),
      y: Math.min(Math.max(y, halfTall), 1 - halfTall),
    };
  };

  const placeBox = (at) => {
    box.style.bottom = 'auto';
    box.style.left = (at.x * 100) + '%';
    box.style.top = (at.y * 100) + '%';
    box.style.transform = 'translate(-50%, -50%)';
  };

  // Tabbing away with the key down would otherwise leave it armed forever.
  const armBox = (on) => box.classList.toggle('is-movable', on);
  window.addEventListener('keydown', (e) => { if (e.key === 'Shift') armBox(true); });
  window.addEventListener('keyup', (e) => { if (e.key === 'Shift') armBox(false); });
  window.addEventListener('blur', () => armBox(false));

  box.addEventListener('pointerdown', (event) => {
    if (event.pointerType !== 'mouse' || !event.shiftKey || !stage) return;
    event.preventDefault();
    try { box.setPointerCapture(event.pointerId); } catch (e) { /* pointer gone */ }

    const bounds = stage.getBoundingClientRect();
    const rect = box.getBoundingClientRect();
    const centre = {
      x: (rect.left + rect.width / 2 - bounds.left) / bounds.width,
      y: (rect.top + rect.height / 2 - bounds.top) / bounds.height,
    };
    boxGrab = {
      pointerId: event.pointerId,
      x: centre.x - (event.clientX - bounds.left) / bounds.width,
      y: centre.y - (event.clientY - bounds.top) / bounds.height,
    };
    box.classList.add('is-dragging');
    placeBox(insideStage(centre.x, centre.y));
  });

  box.addEventListener('pointermove', (event) => {
    if (!boxGrab || !stage) return;
    const bounds = stage.getBoundingClientRect();
    placeBox(insideStage(
      (event.clientX - bounds.left) / bounds.width + boxGrab.x,
      (event.clientY - bounds.top) / bounds.height + boxGrab.y
    ));
  });

  ['pointerup', 'pointercancel', 'lostpointercapture'].forEach((type) =>
    box.addEventListener(type, () => {
      boxGrab = null;
      box.classList.remove('is-dragging');
    })
  );

  // ── the pointer reveal and the ⌥ stack ────────────────────────────────────
  //
  // Neither of these is drawn. The page has a pointer and something underneath
  // the captions, which is everything the reveal needs, and a keyboard with the
  // same modifier on it, so both are wired to the real thing and behave as they
  // do in the app. The geometry is in styles.css, against the app's own
  // constants; what is here is where the hole is and what is in the stack.

  const history = document.getElementById('caption-history');
  const screen = document.querySelector('.demo-screen');

  // Closed pages, oldest first. `defaultHistoryDepth` is 15 in the app; this
  // stage is a few hundred pixels tall and would clip most of them, so it keeps
  // what the room can nearly show and lets the fade say there is more.
  const PAST_MAX = 6;
  const past = [];

  // Deduplicated against the last entry, as the app's own closePage is: a page
  // can close twice in a beat, and two identical boxes read as a stutter rather
  // than as history.
  const closePage = (line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed === past[past.length - 1]) return;
    past.push(trimmed);
    if (past.length > PAST_MAX) past.splice(0, past.length - PAST_MAX);
    if (history && history.classList.contains('is-visible')) paintHistory();
  };

  // Vertical space for the stack on one side of the live box. The gap is the
  // app's 6pt and the margin off the edge of the screen its 12pt, both at 30pt
  // of text, so both in em.
  const roomFor = (above, rect, bounds, em) =>
    (above ? rect.top - bounds.top : bounds.bottom - rect.bottom) - em * 0.6;

  // Which side of the live box the stack takes. Decided on the press that raises
  // it and held for as long as it is up: re-deciding it as the box resizes would
  // let one sentence wrapping to a second line throw the stack across it
  // mid-read, which is the app's reasoning too.
  let placedAbove = true;

  // Below this there is not enough room to be worth drawing: the app's 40pt.
  const MIN_ROOM = 1.33;

  // Pinned to the live box, so dragging the captions takes the stack with them.
  const placeHistory = () => {
    if (!history || !stage) return;
    const bounds = stage.getBoundingClientRect();
    const rect = box.getBoundingClientRect();
    const em = parseFloat(getComputedStyle(history).fontSize) || 16;
    const room = roomFor(placedAbove, rect, bounds, em);

    history.style.left = ((rect.left + rect.width / 2 - bounds.left) / bounds.width * 100) + '%';
    if (placedAbove) {
      history.style.top = 'auto';
      history.style.bottom = ((bounds.bottom - rect.top + em * 0.2) / bounds.height * 100) + '%';
    } else {
      history.style.bottom = 'auto';
      history.style.top = ((rect.bottom - bounds.top + em * 0.2) / bounds.height * 100) + '%';
    }
    history.style.maxHeight = Math.max(0, room) + 'px';

    // Nowhere left to put it. Hidden rather than emptied, because the live box
    // shrinks again on the next page and the stack should still be there.
    history.classList.toggle('is-starved', room < em * MIN_ROOM);
    history.classList.toggle('is-clipped', history.scrollHeight > room + 1);
    // Parked against the live box, which is the end the newest box arrives at
    // and the one somebody holding ⌥ is reaching for.
    history.scrollTop = placedAbove ? history.scrollHeight : 0;
  };

  // Reconciled rather than rebuilt, so that a box already on screen is not
  // animated again when a page closes while ⌥ is still held — only the one that
  // just closed rises. The app does the same, against the same problem.
  const paintHistory = () => {
    if (!history) return;
    const carried = new Map();
    [...history.children].forEach((el) => {
      if (!carried.has(el.textContent)) carried.set(el.textContent, el);
    });

    // Reversed when the stack hangs below, so the newest box is the one touching
    // the live box either way.
    const ordered = placedAbove ? past : [...past].reverse();

    const risen = [];
    history.textContent = '';
    ordered.forEach((line) => {
      let el = carried.get(line);
      if (el) {
        carried.delete(line);
      } else {
        el = document.createElement('div');
        el.className = 'hist-line';
        el.textContent = line;
        risen.push(el);
      }
      history.appendChild(el);
    });

    // Nearest the live box first, so the stack unrolls out of it. Which end that
    // is depends on the side: the newest box is last above it and first below.
    const kids = [...history.children];
    risen.forEach((el) => {
      const i = kids.indexOf(el);
      el.style.setProperty('--rise', placedAbove ? kids.length - 1 - i : i);
      el.classList.add('is-rising');
    });

    placeHistory();
  };

  const showHistory = (on) => {
    if (!history || !stage) return;
    const want = on && past.length > 0;

    if (want) {
      // A fresh press builds the stack from nothing, so every box rises. Only
      // while ⌥ is still held does the reconciliation in paintHistory matter,
      // and then it is a single box that just closed, joining a stack that is
      // already up. The app draws the same line.
      if (!history.classList.contains('is-visible')) history.textContent = '';

      // Flip only when there is genuinely more room the other way, which is what
      // makes the stack fall below the box once the box is dragged to the top.
      const bounds = stage.getBoundingClientRect();
      const rect = box.getBoundingClientRect();
      const em = parseFloat(getComputedStyle(history).fontSize) || 16;
      placedAbove = roomFor(true, rect, bounds, em) >= roomFor(false, rect, bounds, em);
      history.classList.toggle('is-below', !placedAbove);
      paintHistory();
    }
    // The boxes are left in place on the way out so the stack fades rather than
    // vanishing; the next press is what clears them.
    history.classList.toggle('is-visible', want);
    box.classList.toggle('is-solid', want);
    queueHole();
  };

  // Where the pointer is, in the page's coordinates. Kept rather than the hole's
  // offset because the box moves under a still pointer far more than the pointer
  // moves over a still box: it re-centres and re-sizes on every word, and the
  // app recomputes the centre on exactly the same events for the same reason.
  let pointer = null;
  let holeQueued = false;

  const paintHole = () => {
    // ⇧ keeps the box solid, the way it does in the app: you are about to pick
    // it up, and a hole under the hand you are picking it up with is no help.
    // ⌥ does too, because the stack is what is being read then.
    if (!pointer || box.classList.contains('is-movable') || box.classList.contains('is-solid')) {
      box.style.setProperty('--hole-x', '-999px');
      box.style.setProperty('--hole-y', '-999px');
      return;
    }
    const rect = box.getBoundingClientRect();
    box.style.setProperty('--hole-x', (pointer.x - rect.left) + 'px');
    box.style.setProperty('--hole-y', (pointer.y - rect.top) + 'px');
  };

  // One paint a frame at most. The box resizes on every word and the pointer
  // reports faster than that, so both feed the same queue.
  const queueHole = () => {
    if (holeQueued) return;
    holeQueued = true;
    requestAnimationFrame(() => {
      holeQueued = false;
      paintHole();
      if (history && history.classList.contains('is-visible')) placeHistory();
    });
  };

  if (screen) {
    screen.addEventListener('pointermove', (event) => {
      if (event.pointerType !== 'mouse') return;
      pointer = { x: event.clientX, y: event.clientY };
      queueHole();
    });
    // Nothing to turn off: the falloff means distance alone ends the reveal, on
    // this screen as on a real one. This is only for the pointer that leaves in
    // one jump, or out of the window entirely.
    screen.addEventListener('pointerleave', () => { pointer = null; queueHole(); });
  }

  // The box changes width on almost every word, which moves its left edge by
  // most of the box. Without this the hole lands off the pointer until the
  // pointer next moves, and reads as the reveal blinking out.
  if (typeof ResizeObserver === 'function') new ResizeObserver(queueHole).observe(box);

  // Tabbing away with either key down would otherwise leave it armed forever,
  // the same reason armBox watches blur.
  window.addEventListener('keydown', (e) => {
    // Held keys repeat, and a repeat that repainted would restart the stagger
    // over and over for as long as ⌥ is down.
    if (e.key === 'Alt' && !e.repeat) showHistory(true);
    if (e.key === 'Shift') queueHole();
  });
  window.addEventListener('keyup', (e) => {
    if (e.key === 'Alt') showHistory(false);
    if (e.key === 'Shift') queueHole();
  });
  window.addEventListener('blur', () => showHistory(false));

  // Only run while the demo is actually on screen...
  new IntersectionObserver(
    ([entry]) => { onScreen = entry.isIntersecting; sync(); },
    { threshold: 0.15 }
  ).observe(box);

  // ...and only while the tab is in front: timers in a backgrounded tab are
  // throttled to about one a second, which would wreck the pacing.
  document.addEventListener('visibilitychange', sync);

  loop();
})();
