#!/bin/bash
# Vendors the website's caption demo into the app, for the About window's webview.
#
# The demo is the one thing on subtitles-live.com that shows what the app does
# without installing it, and it is plain HTML, CSS and JS — so it can be lifted
# whole rather than rebuilt in AppKit. It is copied rather than fetched: an About
# box that phones home would be an odd thing to ship in an app whose entire pitch
# is that nothing leaves the machine.
#
# Copied means it drifts. This script is the answer to that — re-run it after the
# site's demo changes rather than hand-editing anything under app/macos/Demo/:
#
#   ./tools/vendor-demo.sh ../subtitles-site
#
# Everything it writes is generated. The only hand-written file there is
# demo.html, which wraps these in a page and overrides what the embedding needs.
set -euo pipefail

cd "$(dirname "$0")/.."
SITE="${1:-../subtitles-site}"
OUT="app/macos/Demo"

for f in index.html styles.css script.js; do
  [ -f "$SITE/$f" ] || { echo "!! no $f in $SITE — pass the site checkout as \$1" >&2; exit 1; }
done

# Line ranges, not markers: the site's files have no extraction markers in them
# and adding some would be a change to that repo for this one's benefit. The
# guards below are what catches them going stale.
extract() { # file first last
  awk -v a="$2" -v b="$3" 'NR >= a && NR <= b' "$SITE/$1"
}

expect() { # description text pattern
  grep -q -- "$3" <<<"$2" || {
    echo "!! $1 does not look right — the site's line numbers have moved." >&2
    echo "   Re-check the ranges in $0 against $SITE." >&2
    exit 1
  }
}

mkdir -p "$OUT"

# ── markup: the .demo block, minus its caption ──
# The caption is a paragraph of page copy, and the welcome window draws its own
# ⇧ line in AppKit instead: text rendered by a web view inside a native window
# is text that does not match anything around it.
HTML=$(extract index.html 378 654)
expect "the demo markup" "$HTML" '<div class="demo[^"]*" id="demo">'
expect "the scene buttons" "$HTML" 'class="demo-scenes"'
# And what the range stops short of. Every check above looks at the start of a
# slice, and a section that has grown a new tail still contains all of them —
# so the vendor succeeds with the demo's newest half missing. Twice now the
# ranges have gone stale that way. The lines just past each range say whether
# it still ends where the section does.
expect "the end of the demo markup" "$(extract index.html 655 660)" 'demo-caption'
{
  echo "<!-- Generated by tools/vendor-demo.sh from the site's index.html. Do not edit. -->"
  echo "$HTML"
  echo "      </div>"
} > "$OUT/demo.html.part"

# ── styles: the palettes, then the demo section ──
# The palettes come along because every colour in the demo is a var() into them,
# and the two dark blocks because the webview follows the system appearance.
CSS_ROOT=$(extract styles.css 1 96)
CSS_DEMO=$(extract styles.css 736 2051)
expect "the light palette" "$CSS_ROOT" -- '--desktop-bg\|:root {'
expect "the dark palette" "$CSS_ROOT" 'prefers-color-scheme: dark'
expect "the demo styles" "$CSS_DEMO" '^\.demo {'
expect "the scene buttons' styles" "$CSS_DEMO" '^\.demo-scenes {'
expect "the end of the demo styles" "$(extract styles.css 2052 2056)" 'sections'
# The frame is the redesign's box around the screen and lives with the hero's
# styles, a long way past the demo section. It changes nothing at this window's
# width, but it is the demo's own rule and belongs with the rest.
CSS_FRAME=$(extract styles.css 2821 2830)
expect "the demo frame" "$CSS_FRAME" '^\.demo-frame {'
expect "the end of the demo frame" "$(extract styles.css 2831 2833)" 'works with'
{
  echo "/* Generated by tools/vendor-demo.sh from the site's styles.css. Do not edit. */"
  echo "$CSS_ROOT"
  echo "$CSS_DEMO"
  echo
  echo "$CSS_FRAME"
} > "$OUT/demo.css"

# ── behaviour: the menu bar clock and the demo itself ──
# The other IIFEs in the site's script — theme toggle, sticky header, language
# switcher, launch promo — belong to the page, not the demo, and have nothing to
# bind to here anyway.
#
# I18N comes along because the demo's own copy goes through it. On the site it
# reads the translations out of a <template> in the page; there is no template
# here, so every call falls back to the English literal it was given.
JS_I18N=$(extract script.js 8 20)
JS_WAVE=$(extract script.js 96 127)
JS=$(extract script.js 221 1253)
expect "the i18n helper" "$JS_I18N" 'const I18N = '
# waveFit sits among the page's IIFEs but is the demo's: it fits the podcast
# window's waveform to whole device pixels, and the stylesheet's layout of the
# bars is only what stands in until it runs.
expect "the waveform fitter" "$JS_WAVE" 'function waveFit'
expect "the end of the waveform fitter" "$(extract script.js 128 129)" 'function navToggle'
expect "the menu bar clock" "$JS" 'function menuBarClock'
expect "the caption demo" "$JS" 'function captionDemo'
# The demo is the last thing in the site's script, so its range ends at the end
# of the file. Anything after line 1253 is the demo having grown past it.
if [ "$(grep -c "" "$SITE/script.js")" != 1253 ]; then
  echo "!! the demo script does not end where it used to — the site's line numbers have moved." >&2
  echo "   Re-check the ranges in $0 against $SITE." >&2
  exit 1
fi
{
  echo "// Generated by tools/vendor-demo.sh from the site's script.js. Do not edit."
  echo "$JS_I18N"
  echo
  echo "$JS_WAVE"
  echo
  echo "$JS"
} > "$OUT/demo.js"

# demo.html is hand-written and carries the embedding's own overrides; the markup
# above is spliced into it so the one file is what the webview loads.
python3 - "$OUT" <<'PY'
import pathlib, sys
out = pathlib.Path(sys.argv[1])
shell = (out / "demo.shell.html").read_text()
part = (out / "demo.html.part").read_text()
token = "<!--" + "DEMO" + "-->"   # split, so this file holds no copy of it either
if shell.count(token) != 1:
    raise SystemExit(f"!! demo.shell.html has {shell.count(token)} placeholders, expected 1")
(out / "demo.html").write_text(shell.replace(token, part))
PY
rm -f "$OUT/demo.html.part"

echo "vendored into $OUT:"
for f in demo.html demo.css demo.js; do
  printf "    %-10s %s lines\n" "$f" "$(grep -c "" "$OUT/$f")"
done
