#!/bin/bash
# Vendors the website's caption demo into the app, for the About window's webview.
#
# The demo is the one thing on subtitles-live.com that shows what the app does
# without installing it, and it is plain HTML, CSS and JS — so it can be lifted
# whole rather than rebuilt in AppKit. It is copied rather than fetched: an About
# box that phones home would be an odd thing to ship in an app whose entire pitch
# is that nothing leaves the machine.
#
# Copied means it drifts. This script is the answer to that — re-run it after the
# site's demo changes rather than hand-editing anything under app/macos/Demo/:
#
#   ./tools/vendor-demo.sh ../subtitles-site
#
# Everything it writes is generated. The only hand-written file there is
# demo.shell.html, which wraps these in a page and overrides what the embedding
# needs; demo.html is spliced out of it.
set -euo pipefail

cd "$(dirname "$0")/.."
SITE="${1:-../subtitles-site}"
OUT="app/macos/Demo"

for f in index.html styles.css script.js; do
  [ -f "$SITE/$f" ] || { echo "!! no $f in $SITE — pass the site checkout as \$1" >&2; exit 1; }
done

# Line ranges, not markers: the site's files have no extraction markers in them
# and adding some would be a change to that repo for this one's benefit. The
# guards below are what catches them going stale.
extract() { # file first last
  awk -v a="$2" -v b="$3" 'NR >= a && NR <= b' "$SITE/$1"
}

expect() { # description text pattern
  grep -q -- "$3" <<<"$2" || {
    echo "!! $1 does not look right — the site's line numbers have moved." >&2
    echo "   Re-check the ranges in $0 against $SITE." >&2
    exit 1
  }
}

mkdir -p "$OUT"

# ── markup: the .demo block, minus its caption ──
# The caption is a paragraph of page copy, and the welcome window draws its own
# ⇧ line in AppKit instead: text rendered by a web view inside a native window
# is text that does not match anything around it.
HTML=$(extract index.html 381 635)
expect "the demo markup" "$HTML" '<div class="demo[^"]*" id="demo">'
expect "the scene buttons" "$HTML" 'class="demo-scenes"'
# And what the range stops short of. Every check above looks at the start of a
# slice, and a section that has grown a new tail still contains all of them —
# so the vendor succeeds with the demo's newest half missing. Twice now the
# ranges have gone stale that way. The lines just past each range say whether
# it still ends where the section does.
expect "the end of the demo markup" "$(extract index.html 636 641)" 'demo-caption'
# The ⌘-tab switcher wears the apps' icons, which the site keeps as files under
# /assets and the markup names by absolute path. The webview loads a file URL,
# so an absolute path would resolve against the root of the disk: the icons the
# markup names are copied in beside it, and the paths made relative. The
# directory is rebuilt from nothing so an icon the demo stops naming leaves.
rm -rf "$OUT/assets"
# grep's no-match status would fail the pipeline under pipefail, and a demo that
# names no icons is not an error.
{ grep -o 'src="/assets/[^"]*"' <<<"$HTML" || true; } | sed 's/^src="\///; s/"$//' | sort -u |
while read -r icon; do
  [ -f "$SITE/$icon" ] || { echo "!! the demo names $icon, which $SITE does not have" >&2; exit 1; }
  mkdir -p "$OUT/$(dirname "$icon")"
  cp "$SITE/$icon" "$OUT/$icon"
done
HTML=$(sed 's|src="/assets/|src="assets/|g' <<<"$HTML")
# Anything else rooted at / is a file the bundle does not carry.
if grep -q '\(src\|href\)="/' <<<"$HTML"; then
  echo "!! the demo markup names a file by absolute path that this script does not copy:" >&2
  grep -o '\(src\|href\)="/[^"]*"' <<<"$HTML" >&2
  exit 1
fi
{
  echo "<!-- Generated by tools/vendor-demo.sh from the site's index.html. Do not edit. -->"
  echo "$HTML"
  echo "      </div>"
} > "$OUT/demo.html.part"

# ── styles: the palettes, then the demo section ──
# The palettes come along because every colour in the demo is a var() into them,
# and the two dark blocks because the webview follows the system appearance.
CSS_ROOT=$(extract styles.css 1 96)
CSS_DEMO=$(extract styles.css 760 2332)
expect "the light palette" "$CSS_ROOT" -- '--desktop-bg\|:root {'
expect "the dark palette" "$CSS_ROOT" 'prefers-color-scheme: dark'
expect "the demo styles" "$CSS_DEMO" '^\.demo {'
expect "the scene buttons' styles" "$CSS_DEMO" '^\.demo-scenes {'
expect "the end of the demo styles" "$(extract styles.css 2333 2337)" 'sections'
# The frame is the redesign's box around the screen and lives with the hero's
# styles, a long way past the demo section. It changes nothing at this window's
# width, but it is the demo's own rule and belongs with the rest.
CSS_FRAME=$(extract styles.css 3145 3154)
expect "the demo frame" "$CSS_FRAME" '^\.demo-frame {'
expect "the end of the demo frame" "$(extract styles.css 3155 3157)" 'works with'
# The Notes window is drawn as Notes: the toolbar in its title bar, the three
# columns under it. Those styles sit with the landing pages' windows, further
# past the demo section again, because the landing demos draw the same window.
CSS_NOTES=$(extract styles.css 3938 4057)
expect "the Notes window's styles" "$CSS_NOTES" '^\.app-notes '
expect "the Notes window's columns" "$CSS_NOTES" '^\.nt-side {'
expect "the end of the Notes window's styles" "$(extract styles.css 4058 4060)" 'Visual Studio Code'
{
  echo "/* Generated by tools/vendor-demo.sh from the site's styles.css. Do not edit. */"
  echo "$CSS_ROOT"
  echo "$CSS_DEMO"
  echo
  echo "$CSS_FRAME"
  echo
  echo "$CSS_NOTES"
} > "$OUT/demo.css"

# ── behaviour: the menu bar clock and the demo itself ──
# The other IIFEs in the site's script — theme toggle, sticky header, language
# switcher, launch promo — belong to the page, not the demo, and have nothing to
# bind to here anyway.
#
# I18N comes along because the demo's own copy goes through it. On the site it
# reads the translations out of a <template> in the page; there is no template
# here, so every call falls back to the English literal it was given.
JS_I18N=$(extract script.js 8 20)
JS_WAVE=$(extract script.js 203 227)
JS_SEARCH=$(extract script.js 234 770)
JS_WRITE=$(extract script.js 1584 1727)
JS=$(extract script.js 1891 3122)
expect "the i18n helper" "$JS_I18N" 'const I18N = '
# waveFit sits among the page's IIFEs but is the demo's: it fits the podcast
# window's waveform to whole device pixels, and the stylesheet's layout of the
# bars is only what stands in until it runs.
expect "the waveform fitter" "$JS_WAVE" 'function waveFit'
expect "the end of the waveform fitter" "$(extract script.js 227 227)" '^})();$'
# stackSearch is the app's HistorySearchView drawn in the page: the field at the
# stack's edge that pins it and narrows it to the boxes containing the text. The
# caption demo attaches it, so it has to be defined before the demo runs.
expect "the stack search" "$JS_SEARCH" '^const stackSearch = '
expect "the end of the stack search" "$(extract script.js 771 786)" 'function liteDemo'
# liveWriting moves the caret in every window that is a document, the demo's
# notes window among them. It lives with the landing pages' scripts because
# theirs have documents too, but the home demo's notes are what it was drawn for.
expect "the writing animation" "$JS_WRITE" 'function liveWriting'
expect "the end of the writing animation" "$(extract script.js 1728 1730)" 'function navFit'
expect "the menu bar clock" "$JS" 'function menuBarClock'
expect "the caption demo" "$JS" 'function captionDemo'
# The demo used to be the last thing in the site's script, and its range ended
# at the end of the file. The changelog page's release filter follows it now,
# and that is the page's, not the demo's: the lines just past the range say
# whether the demo still ends where it did.
expect "the end of the caption demo" "$(extract script.js 3123 3126)" 'changelog'
{
  echo "// Generated by tools/vendor-demo.sh from the site's script.js. Do not edit."
  echo "$JS_I18N"
  echo
  echo "$JS_WAVE"
  echo
  echo "$JS_SEARCH"
  echo
  echo "$JS_WRITE"
  echo
  echo "$JS"
} > "$OUT/demo.js"

# demo.html is hand-written and carries the embedding's own overrides; the markup
# above is spliced into it so the one file is what the webview loads.
python3 - "$OUT" <<'PY'
import pathlib, sys
out = pathlib.Path(sys.argv[1])
shell = (out / "demo.shell.html").read_text()
part = (out / "demo.html.part").read_text()
token = "<!--" + "DEMO" + "-->"   # split, so this file holds no copy of it either
if shell.count(token) != 1:
    raise SystemExit(f"!! demo.shell.html has {shell.count(token)} placeholders, expected 1")
(out / "demo.html").write_text(shell.replace(token, part))
PY
rm -f "$OUT/demo.html.part"

echo "vendored into $OUT:"
for f in demo.html demo.css demo.js; do
  printf "    %-10s %s lines\n" "$f" "$(grep -c "" "$OUT/$f")"
done
printf "    %-10s %s icons\n" "assets/" "$(find "$OUT/assets" -name '*.png' | wc -l | tr -d ' ')"
