#!/bin/bash
# Vendors the website's caption demo into the app, for the welcome window's webview.
#
# The demo is the one thing on subtitles-live.com that shows what the app does
# without installing it, and it is plain HTML, CSS and JS — so it can be lifted
# whole rather than rebuilt in AppKit. It is copied rather than fetched: a welcome
# window that phones home would be an odd thing to ship in an app whose entire pitch
# is that nothing leaves the machine.
#
# Copied means it drifts. This script is the answer to that — re-run it after the
# site's demo changes rather than hand-editing anything under app/macos/Demo/:
#
#   ./tools/vendor-demo.sh ../subtitles-site
#
# Everything it writes is generated. The only hand-written file there is
# demo.shell.html, which wraps these in a page and overrides what the embedding
# needs; demo.html is spliced out of it.
set -euo pipefail

cd "$(dirname "$0")/.."
SITE="${1:-../subtitles-site}"
OUT="app/macos/Demo"

for f in index.html styles.css script.js; do
  [ -f "$SITE/$f" ] || { echo "!! no $f in $SITE — pass the site checkout as \$1" >&2; exit 1; }
done

# Line ranges, not markers: the site's files have no extraction markers in them
# and adding some would be a change to that repo for this one's benefit. The
# guards below are what catches them going stale.
extract() { # file first last
  awk -v a="$2" -v b="$3" 'NR >= a && NR <= b' "$SITE/$1"
}

expect() { # description text pattern
  grep -q -- "$3" <<<"$2" || {
    echo "!! $1 does not look right — the site's line numbers have moved." >&2
    echo "   Re-check the ranges in $0 against $SITE." >&2
    exit 1
  }
}

mkdir -p "$OUT"

# ── markup: the .demo block, minus its caption ──
# The caption is a paragraph of page copy, and the welcome window draws its own
# ⇧ line in AppKit instead: text rendered by a web view inside a native window
# is text that does not match anything around it.
HTML=$(extract index.html 384 641)
expect "the demo markup" "$HTML" '<div class="demo[^"]*" id="demo">'
expect "the scene buttons" "$HTML" 'class="demo-scenes"'
# And what the range stops short of. Every check above looks at the start of a
# slice, and a section that has grown a new tail still contains all of them —
# so the vendor succeeds with the demo's newest half missing. Twice now the
# ranges have gone stale that way. The lines just past each range say whether
# it still ends where the section does.
expect "the end of the demo markup" "$(extract index.html 642 647)" 'demo-caption'
# The ⌘-tab switcher wears the apps' icons, which the site keeps as files under
# /assets and the markup names by absolute path. The webview loads a file URL,
# so an absolute path would resolve against the root of the disk: the icons the
# markup names are copied in beside it, and the paths made relative. The
# directory is rebuilt from nothing so an icon the demo stops naming leaves.
rm -rf "$OUT/assets"
# grep's no-match status would fail the pipeline under pipefail, and a demo that
# names no icons is not an error.
{ grep -o 'src="/assets/[^"]*"' <<<"$HTML" || true; } | sed 's/^src="\///; s/"$//' | sort -u |
while read -r icon; do
  [ -f "$SITE/$icon" ] || { echo "!! the demo names $icon, which $SITE does not have" >&2; exit 1; }
  mkdir -p "$OUT/$(dirname "$icon")"
  cp "$SITE/$icon" "$OUT/$icon"
done
# The boxes' app rows name their icon from the window playing: the script
# builds `/assets/apps/dock/<data-audio>.png` from the markup's attribute, so
# those icons are named by the attribute rather than by a src, and copied by
# it.
{ grep -o 'data-audio="[a-z]*"' <<<"$HTML" || true; } | sed 's/^data-audio="//; s/"$//' | sort -u |
while read -r app; do
  icon="assets/apps/dock/$app.png"
  [ -f "$SITE/$icon" ] || { echo "!! the demo plays $app, whose icon $SITE does not have" >&2; exit 1; }
  mkdir -p "$OUT/assets/apps/dock"
  cp "$SITE/$icon" "$OUT/$icon"
done
# The settings preview's stand-in app is Google Meet, the call the demo runs,
# drawn as the Dock draws it — named by SettingsPreview.swift rather than by
# the markup, so copied by name.
mkdir -p "$OUT/assets/apps/dock"
cp "$SITE/assets/apps/dock/meet.png" "$OUT/assets/apps/dock/meet.png"
HTML=$(sed 's|src="/assets/|src="assets/|g' <<<"$HTML")
# Anything else rooted at / is a file the bundle does not carry.
if grep -q '\(src\|href\)="/' <<<"$HTML"; then
  echo "!! the demo markup names a file by absolute path that this script does not copy:" >&2
  grep -o '\(src\|href\)="/[^"]*"' <<<"$HTML" >&2
  exit 1
fi
{
  echo "<!-- Generated by tools/vendor-demo.sh from the site's index.html. Do not edit. -->"
  echo "$HTML"
  echo "      </div>"
} > "$OUT/demo.html.part"

# ── styles: the palettes, then the demo section ──
# The palettes come along because every colour in the demo is a var() into them,
# and the two dark blocks because the webview follows the system appearance.
CSS_ROOT=$(extract styles.css 1 96)
CSS_DEMO=$(extract styles.css 761 2652)
expect "the light palette" "$CSS_ROOT" -- '--desktop-bg\|:root {'
expect "the dark palette" "$CSS_ROOT" 'prefers-color-scheme: dark'
expect "the demo styles" "$CSS_DEMO" '^\.demo {'
expect "the scene buttons' styles" "$CSS_DEMO" '^\.demo-scenes {'
expect "the end of the demo styles" "$(extract styles.css 2653 2657)" 'sections'
# The app's menu, dropped from the status item in the demo's first scene, is
# styled with the landing pages' windows rather than in the demo section,
# because those pages drop the same menu. Vendored without it the menu is a
# bare list of ticks and words.
CSS_MENU=$(extract styles.css 3937 4083)
expect "the menu's styles" "$CSS_MENU" '^\.mn-root {'
expect "the end of the menu's styles" "$(extract styles.css 4084 4084)" 'landing pages'
# The frame is the redesign's box around the screen and lives with the hero's
# styles, a long way past the demo section. It changes nothing at this window's
# width, but it is the demo's own rule and belongs with the rest.
CSS_FRAME=$(extract styles.css 3485 3494)
expect "the demo frame" "$CSS_FRAME" '^\.demo-frame {'
expect "the end of the demo frame" "$(extract styles.css 3495 3497)" 'works with'
# The Notes window is drawn as Notes: the toolbar in its title bar, the three
# columns under it. Those styles sit with the landing pages' windows, further
# past the demo section again, because the landing demos draw the same window.
CSS_NOTES=$(extract styles.css 4392 4513)
expect "the Notes window's styles" "$CSS_NOTES" '^/\* ── Notes'
expect "the Notes window's columns" "$CSS_NOTES" '^\.nt-side {'
expect "the end of the Notes window's styles" "$(extract styles.css 4514 4516)" 'Visual Studio Code'
# The Tahoe pass: the windows drawn the way macOS 26 draws them — rounder
# frames with a rim, sidebars as glass panes with the traffic lights in them,
# the call's controls as a capsule over the tiles, the menu on the same glass.
# It restyles the demo's windows from the end of the stylesheet, after every
# page's own rules, and without it the windows are the old squarer ones under
# the new markup.
CSS_TAHOE=$(extract styles.css 4859 5103)
expect "the Tahoe styles" "$CSS_TAHOE" '^/\* .* Tahoe '
expect "the Tahoe menu" "$CSS_TAHOE" '^\.mn-panel {'
# It is the last thing in the file, so what says it still ends where it did is
# that nothing follows it: a section added after it would move the end, and
# so would rules added to it.
[ -z "$(extract styles.css 5104 99999)" ] || {
  echo "!! styles.css no longer ends with the Tahoe styles — the site's line numbers have moved." >&2
  echo "   Re-check the ranges in $0 against $SITE." >&2
  exit 1
}
{
  echo "/* Generated by tools/vendor-demo.sh from the site's styles.css. Do not edit. */"
  echo "$CSS_ROOT"
  echo "$CSS_DEMO"
  echo
  echo "$CSS_MENU"
  echo
  echo "$CSS_FRAME"
  echo
  echo "$CSS_NOTES"
  echo
  echo "$CSS_TAHOE"
} > "$OUT/demo.css"

# ── behaviour: the menu bar clock and the demo itself ──
# The other IIFEs in the site's script — theme toggle, sticky header, language
# switcher, launch promo — belong to the page, not the demo, and have nothing to
# bind to here anyway.
#
# I18N comes along because the demo's own copy goes through it. On the site it
# reads the translations out of a <template> in the page; there is no template
# here, so every call falls back to the English literal it was given.
JS_I18N=$(extract script.js 8 20)
# The recording flag, declared just past the i18n helper, and under it the
# settings seed: SETTINGS reads window.SUBTITLES_SETTINGS, which the welcome
# window sets from the app's own settings before this runs (Welcome.swift),
# so the box the demo draws is the box the app is drawing. The caption loop
# reads the flag only for a line with a source — the translation scene's —
# and without it that line threw after its last word and left the box up for
# good.
JS_CAPTURE=$(extract script.js 48 111)
JS_WAVE=$(extract script.js 290 314)
JS_SEARCH=$(extract script.js 321 2029)
JS_WRITE=$(extract script.js 2963 3106)
JS=$(extract script.js 3283 4741)
expect "the i18n helper" "$JS_I18N" 'const I18N = '
expect "the recording flag" "$JS_CAPTURE" '^const CAPTURE = '
expect "the settings seed" "$JS_CAPTURE" '^const SETTINGS = '
expect "the end of the settings seed" "$(extract script.js 112 113)" 'function theme'
# waveFit sits among the page's IIFEs but is the demo's: it fits the podcast
# window's waveform to whole device pixels, and the stylesheet's layout of the
# bars is only what stands in until it runs.
expect "the waveform fitter" "$JS_WAVE" 'function waveFit'
expect "the end of the waveform fitter" "$(extract script.js 314 314)" '^})();$'
# Everything the caption demo shares with the landing pages' demos, from the
# stack's helpers to the window resizing: the boxes' icon rows, the keycaps,
# the ⇧ ring, the name tab, the settings seed's defaults and what dresses a
# demo to them, the pointer reveal, the app's menu, stackSearch — the app's
# HistorySearchView drawn in the page — and the windows' moving and resizing.
# All of it has to be defined before the demo runs.
expect "the stack search" "$JS_SEARCH" '^const stackSearch = '
expect "the settings seed's defaults" "$JS_SEARCH" '^const DEMO_DEFAULTS = '
expect "the app's menu" "$JS_SEARCH" '^const statusMenu = '
expect "the window resizing" "$JS_SEARCH" '^const windowResize = '
expect "the end of the stack search" "$(extract script.js 2030 2045)" 'function liteDemo'
# liveWriting moves the caret in every window that is a document, the demo's
# notes window among them. It lives with the landing pages' scripts because
# theirs have documents too, but the home demo's notes are what it was drawn for.
expect "the writing animation" "$JS_WRITE" 'function liveWriting'
expect "the end of the writing animation" "$(extract script.js 3107 3109)" 'function navFit'
expect "the menu bar clock" "$JS" 'function menuBarClock'
expect "the caption demo" "$JS" 'function captionDemo'
# The demo used to be the last thing in the site's script, and its range ended
# at the end of the file. The changelog page's release filter follows it now,
# and that is the page's, not the demo's: the lines just past the range say
# whether the demo still ends where it did.
expect "the end of the caption demo" "$(extract script.js 4742 4745)" 'changelog'
ALLJS=$(
  echo "// Generated by tools/vendor-demo.sh from the site's script.js. Do not edit."
  echo "$JS_I18N"
  echo
  echo "$JS_CAPTURE"
  echo
  echo "$JS_WAVE"
  echo
  echo "$JS_SEARCH"
  echo
  echo "$JS_WRITE"
  echo
  echo "$JS"
)
# The script names the boxes' icons by root path too — see the markup above
# for why that cannot stand in a file URL — and is rewritten the same way.
# On the whole of it, not one slice: the function that builds the path sits
# with the stack search, since the stack's boxes wear the row as well.
ALLJS=$(sed "s|'/assets/|'assets/|g" <<<"$ALLJS")
if grep -q "['\"]/assets/" <<<"$ALLJS"; then
  echo "!! the demo script names a file by absolute path that this script does not rewrite:" >&2
  grep -o "['\"]/assets/[^'\"]*" <<<"$ALLJS" >&2
  exit 1
fi
printf '%s\n' "$ALLJS" > "$OUT/demo.js"

# demo.html is hand-written and carries the embedding's own overrides; the markup
# above is spliced into it so the one file is what the webview loads.
python3 - "$OUT" <<'PY'
import pathlib, sys
out = pathlib.Path(sys.argv[1])
shell = (out / "demo.shell.html").read_text()
part = (out / "demo.html.part").read_text()
token = "<!--" + "DEMO" + "-->"   # split, so this file holds no copy of it either
if shell.count(token) != 1:
    raise SystemExit(f"!! demo.shell.html has {shell.count(token)} placeholders, expected 1")
(out / "demo.html").write_text(shell.replace(token, part))
PY
rm -f "$OUT/demo.html.part"

echo "vendored into $OUT:"
for f in demo.html demo.css demo.js; do
  printf "    %-10s %s lines\n" "$f" "$(grep -c "" "$OUT/$f")"
done
printf "    %-10s %s icons\n" "assets/" "$(find "$OUT/assets" -name '*.png' | wc -l | tr -d ' ')"
